/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2022-08-01 22:45:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/tld/vgc-util.tld", Long.valueOf(1646829840000L));
    _jspx_dependants.put("/WEB-INF/tld/struts-html.tld", Long.valueOf(1646829840000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005faction_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005faction_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.release();
    _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.release();
    _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005faction_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Modificado por: Kerwin Arias (02/09/2012) -->\n");
      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Frameset//EN\">\n");
      out.write("<html>\n");
      out.write("	<head>\n");
      out.write("		<title>");
      if (_jspx_meth_vgcutil_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("</title>\n");
      out.write("		<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      if (_jspx_meth_html_005frewrite_005f0(_jspx_page_context))
        return;
      out.write("\">\n");
      out.write("		<META http-equiv=\"Content-Type\" content=\"text/html;CHARSET=iso-8859-1\">\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/componentes/ajax/ajaxJs.jsp", out, true);
      out.write("\n");
      out.write("		<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_html_005frewrite_005f1(_jspx_page_context))
        return;
      out.write("\"></script>\n");
      out.write("		<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("			// Declaración de las variables globales\n");
      out.write("			var IE = navigator.appName == \"Microsoft Internet Explorer\";\n");
      out.write("			var NS = navigator.appName == \"Netscape\";\n");
      out.write("			var bVer = parseInt(navigator.appVersion);\n");
      out.write("			var ventana;\n");
      out.write("\n");
      out.write("			function abrirAplicacion() \n");
      out.write("			{\n");
      out.write("				var estilo;\n");
      out.write("				var alto = (screen.height - 88);\n");
      out.write("				var ancho = (screen.width - 10);\n");
      out.write("			\n");
      out.write("				//Para el caso de Internet Explorer\n");
      out.write("				if (IE) \n");
      out.write("				{\n");
      out.write("					alto = (screen.height - 88);\n");
      out.write("					ancho = (screen.width - 10);\n");
      out.write("			\n");
      out.write("					alto = screen.availHeight - 50;\n");
      out.write("					ancho = screen.availWidth - 10;\n");
      out.write("				}\n");
      out.write("			\n");
      out.write("				//Para el caso de Mozilla Firefox\n");
      out.write("				if (NS) \n");
      out.write("				{\n");
      out.write("					alto = (screen.height - 85);\n");
      out.write("					ancho = (screen.width - 6);\n");
      out.write("			\n");
      out.write("					alto = screen.availHeight - 60;\n");
      out.write("					ancho = screen.availWidth - 15;\n");
      out.write("				}\n");
      out.write("			\n");
      out.write("				estilo = \"toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, fullscreen=yes, type=fullWindow, left=0, top=0, width=\" + ancho + \", height=\" + alto;\n");
      out.write("				// estilo = \"toolbar=yes, location=yes, directories=yes, status=yes, menubar=yes, scrollbars=yes, resizable=yes, left=0, top=0, width=\" + ancho + \", height=\" + alto;\n");
      out.write("				ventana = window.open(\"ingreso.action?pantallaAlto=\" + alto + \"&pantallaAncho=\" + ancho + \"&navegadorNombre=\" + navigator.appName + \"&navegadorVersion=\" + navigator.appVersion + \"&sesId=");
      out.print( request.getSession().getId() );
      out.write("\" + \"&versionApp=\" + '");
      if (_jspx_meth_vgcutil_005fmessage_005f1(_jspx_page_context))
        return;
      out.write("' + \"&buildApp=\" + '");
      if (_jspx_meth_vgcutil_005fmessage_005f2(_jspx_page_context))
        return;
      out.write("' + \"&fechaApp=\" + '");
      if (_jspx_meth_vgcutil_005fmessage_005f3(_jspx_page_context))
        return;
      out.write("', \"");
      if (_jspx_meth_vgcutil_005fmessage_005f4(_jspx_page_context))
        return;
      out.write("\", estilo, 'replace');\n");
      out.write("				\n");
      out.write("				var timer = setInterval(function() \n");
      out.write("				{   \n");
      out.write("				    if(ventana.closed) \n");
      out.write("				    {  \n");
      out.write("				        clearInterval(timer);  \n");
      out.write("				        ajaxSendRequestReceiveInputSincronica('GET', '");
      if (_jspx_meth_html_005frewrite_005f2(_jspx_page_context))
        return;
      out.write("', null, 'usuarioLoggedOut()');\n");
      out.write("				       // window.location.href='");
      if (_jspx_meth_html_005frewrite_005f3(_jspx_page_context))
        return;
      out.write("';\n");
      out.write("				    }  \n");
      out.write("				}, 200);\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			function usuarioLoggedOut()\n");
      out.write("			{\n");
      out.write("				closeAppWindows();\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			function closeAppWindows() \n");
      out.write("			{\n");
      out.write("				ventana.close();\n");
      out.write("				setInterval(function() \n");
      out.write("				{\n");
      out.write("					window.close();\n");
      out.write("				}, 200);\n");
      out.write("				return false;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			abrirAplicacion();\n");
      out.write("			document.onkeydown = mykeyhandler;\n");
      out.write("\n");
      out.write("			function mykeyhandler() \n");
      out.write("			{\n");
      out.write("				if(event.altLeft && window.event.keyCode == 37 || event.ctrlKey)\n");
      out.write("					alert('");
      if (_jspx_meth_vgcutil_005fmessage_005f5(_jspx_page_context))
        return;
      out.write("');\n");
      out.write("				if ((window.event && window.event.keyCode == 116) || (window.event && window.event.keyCode == 122)) \n");
      out.write("				{\n");
      out.write("					// try to cancel the backspace\n");
      out.write("					window.event.cancelBubble = true;\n");
      out.write("					window.event.keyCode = 8;\n");
      out.write("					window.event.returnValue = false;\n");
      out.write("					return false;\n");
      out.write("				}\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			function clickIE() \n");
      out.write("			{\n");
      out.write("				if (document.all) \n");
      out.write("					return false;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			function clickNS(e) \n");
      out.write("			{\n");
      out.write("				if (document.layers ||(document.getElementById && !document.all)) \n");
      out.write("				{\n");
      out.write("					if (e.which == 2 || e.which == 3) \n");
      out.write("						return false;\n");
      out.write("				}\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			if (document.layers) \n");
      out.write("			{\n");
      out.write("				document.captureEvents(Event.MOUSEDOWN);\n");
      out.write("				document.onmousedown = clickNS;\n");
      out.write("			} \n");
      out.write("			else \n");
      out.write("			{\n");
      out.write("				document.onmouseup = clickNS;\n");
      out.write("				document.oncontextmenu = clickIE;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			document.oncontextmenu = new Function(\"return false\");\n");
      out.write("\n");
      out.write("			function mouseDown(e) \n");
      out.write("			{\n");
      out.write("				var ctrlPressed=0;\n");
      out.write("				var altPressed=0;\n");
      out.write("				var shiftPressed=0;\n");
      out.write("				if (parseInt(navigator.appVersion) > 3) \n");
      out.write("				{\n");
      out.write("					if (navigator.appName == \"Netscape\") \n");
      out.write("					{\n");
      out.write("						var mString =(e.modifiers + 32).toString(2).substring(3, 6);\n");
      out.write("						shiftPressed = (mString.charAt(0)==\"1\");\n");
      out.write("						ctrlPressed = (mString.charAt(1)==\"1\");\n");
      out.write("						altPressed = (mString.charAt(2)==\"1\");\n");
      out.write("						self.status = \"modifiers=\" + e.modifiers + \" (\" + mString + \")\";\n");
      out.write("			  		} \n");
      out.write("					else \n");
      out.write("					{\n");
      out.write("						shiftPressed = event.shiftKey;\n");
      out.write("						altPressed = event.altKey;\n");
      out.write("						ctrlPressed = event.ctrlKey;\n");
      out.write("					}\n");
      out.write("					if (shiftPressed || altPressed || ctrlPressed) \n");
      out.write("						alert ('");
      if (_jspx_meth_vgcutil_005fmessage_005f6(_jspx_page_context))
        return;
      out.write("');\n");
      out.write("			 	}\n");
      out.write("				return true;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			if (parseInt(navigator.appVersion) > 3) \n");
      out.write("			{\n");
      out.write("				document.onmousedown = mouseDown;\n");
      out.write("				if (navigator.appName==\"Netscape\")\n");
      out.write("					document.captureEvents(Event.MOUSEDOWN);\n");
      out.write("			}\n");
      out.write("		</script>\n");
      out.write("	</head>\n");
      out.write("\n");
      out.write("	<body class=\"cuerpo\">\n");
      out.write("		<div id=\"fondo\"></div>\n");
      out.write("		<!-- Este es el \"Contenedor Principal\" -->\n");
      out.write("		<table class=\"contenedorBienvenida\">\n");
      out.write("			<!-- Este es el inicio de la aplicación -->\n");
      out.write("			<tr>\n");
      out.write("				<td><img src=\"");
      if (_jspx_meth_html_005frewrite_005f4(_jspx_page_context))
        return;
      out.write("\" border=\"0\" width=\"10\" height=\"10\">&nbsp; <a onMouseOver=\"this.className='mouseEncimaBienvenida'\" onMouseOut=\"this.className='mouseFueraBienvenida'\" href=\"#\" target=\"_self\" class=\"mouseFueraBienvenida\" onClick=\"abrirAplicacion()\">");
      if (_jspx_meth_vgcutil_005fmessage_005f7(_jspx_page_context))
        return;
      out.write(' ');
      if (_jspx_meth_vgcutil_005fmessage_005f8(_jspx_page_context))
        return;
      out.write(' ');
      if (_jspx_meth_vgcutil_005fmessage_005f9(_jspx_page_context))
        return;
      out.write(' ');
      if (_jspx_meth_vgcutil_005fmessage_005f10(_jspx_page_context))
        return;
      out.write(' ');
      if (_jspx_meth_vgcutil_005fmessage_005f11(_jspx_page_context))
        return;
      out.write("</a></td>\n");
      out.write("			</tr>\n");
      out.write("		</table>\n");
      out.write("	</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_vgcutil_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  vgcutil:message
    com.visiongc.commons.struts.tag.MessageTag _jspx_th_vgcutil_005fmessage_005f0 = (com.visiongc.commons.struts.tag.MessageTag) _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.get(com.visiongc.commons.struts.tag.MessageTag.class);
    boolean _jspx_th_vgcutil_005fmessage_005f0_reused = false;
    try {
      _jspx_th_vgcutil_005fmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_vgcutil_005fmessage_005f0.setParent(null);
      // /index.jsp(9,9) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_vgcutil_005fmessage_005f0.setKey("aplicacion.nombre");
      int _jspx_eval_vgcutil_005fmessage_005f0 = _jspx_th_vgcutil_005fmessage_005f0.doStartTag();
      if (_jspx_th_vgcutil_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_vgcutil_005fmessage_005f0);
      _jspx_th_vgcutil_005fmessage_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_vgcutil_005fmessage_005f0, _jsp_getInstanceManager(), _jspx_th_vgcutil_005fmessage_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005frewrite_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:rewrite
    org.apache.struts.taglib.html.RewriteTag _jspx_th_html_005frewrite_005f0 = (org.apache.struts.taglib.html.RewriteTag) _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.get(org.apache.struts.taglib.html.RewriteTag.class);
    boolean _jspx_th_html_005frewrite_005f0_reused = false;
    try {
      _jspx_th_html_005frewrite_005f0.setPageContext(_jspx_page_context);
      _jspx_th_html_005frewrite_005f0.setParent(null);
      // /index.jsp(10,47) name = page type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005frewrite_005f0.setPage("/componentes/estilos/estilos.css");
      int _jspx_eval_html_005frewrite_005f0 = _jspx_th_html_005frewrite_005f0.doStartTag();
      if (_jspx_th_html_005frewrite_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.reuse(_jspx_th_html_005frewrite_005f0);
      _jspx_th_html_005frewrite_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005frewrite_005f0, _jsp_getInstanceManager(), _jspx_th_html_005frewrite_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005frewrite_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:rewrite
    org.apache.struts.taglib.html.RewriteTag _jspx_th_html_005frewrite_005f1 = (org.apache.struts.taglib.html.RewriteTag) _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.get(org.apache.struts.taglib.html.RewriteTag.class);
    boolean _jspx_th_html_005frewrite_005f1_reused = false;
    try {
      _jspx_th_html_005frewrite_005f1.setPageContext(_jspx_page_context);
      _jspx_th_html_005frewrite_005f1.setParent(null);
      // /index.jsp(13,38) name = page type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005frewrite_005f1.setPage("/paginas/comunes/jQuery/js/jquery.min.js");
      int _jspx_eval_html_005frewrite_005f1 = _jspx_th_html_005frewrite_005f1.doStartTag();
      if (_jspx_th_html_005frewrite_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.reuse(_jspx_th_html_005frewrite_005f1);
      _jspx_th_html_005frewrite_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005frewrite_005f1, _jsp_getInstanceManager(), _jspx_th_html_005frewrite_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_vgcutil_005fmessage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  vgcutil:message
    com.visiongc.commons.struts.tag.MessageTag _jspx_th_vgcutil_005fmessage_005f1 = (com.visiongc.commons.struts.tag.MessageTag) _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.get(com.visiongc.commons.struts.tag.MessageTag.class);
    boolean _jspx_th_vgcutil_005fmessage_005f1_reused = false;
    try {
      _jspx_th_vgcutil_005fmessage_005f1.setPageContext(_jspx_page_context);
      _jspx_th_vgcutil_005fmessage_005f1.setParent(null);
      // /index.jsp(50,247) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_vgcutil_005fmessage_005f1.setKey("aplicacion.version");
      int _jspx_eval_vgcutil_005fmessage_005f1 = _jspx_th_vgcutil_005fmessage_005f1.doStartTag();
      if (_jspx_th_vgcutil_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_vgcutil_005fmessage_005f1);
      _jspx_th_vgcutil_005fmessage_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_vgcutil_005fmessage_005f1, _jsp_getInstanceManager(), _jspx_th_vgcutil_005fmessage_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_vgcutil_005fmessage_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  vgcutil:message
    com.visiongc.commons.struts.tag.MessageTag _jspx_th_vgcutil_005fmessage_005f2 = (com.visiongc.commons.struts.tag.MessageTag) _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.get(com.visiongc.commons.struts.tag.MessageTag.class);
    boolean _jspx_th_vgcutil_005fmessage_005f2_reused = false;
    try {
      _jspx_th_vgcutil_005fmessage_005f2.setPageContext(_jspx_page_context);
      _jspx_th_vgcutil_005fmessage_005f2.setParent(null);
      // /index.jsp(50,311) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_vgcutil_005fmessage_005f2.setKey("aplicacion.version.build");
      int _jspx_eval_vgcutil_005fmessage_005f2 = _jspx_th_vgcutil_005fmessage_005f2.doStartTag();
      if (_jspx_th_vgcutil_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_vgcutil_005fmessage_005f2);
      _jspx_th_vgcutil_005fmessage_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_vgcutil_005fmessage_005f2, _jsp_getInstanceManager(), _jspx_th_vgcutil_005fmessage_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_vgcutil_005fmessage_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  vgcutil:message
    com.visiongc.commons.struts.tag.MessageTag _jspx_th_vgcutil_005fmessage_005f3 = (com.visiongc.commons.struts.tag.MessageTag) _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.get(com.visiongc.commons.struts.tag.MessageTag.class);
    boolean _jspx_th_vgcutil_005fmessage_005f3_reused = false;
    try {
      _jspx_th_vgcutil_005fmessage_005f3.setPageContext(_jspx_page_context);
      _jspx_th_vgcutil_005fmessage_005f3.setParent(null);
      // /index.jsp(50,381) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_vgcutil_005fmessage_005f3.setKey("aplicacion.version.fecha");
      int _jspx_eval_vgcutil_005fmessage_005f3 = _jspx_th_vgcutil_005fmessage_005f3.doStartTag();
      if (_jspx_th_vgcutil_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_vgcutil_005fmessage_005f3);
      _jspx_th_vgcutil_005fmessage_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_vgcutil_005fmessage_005f3, _jsp_getInstanceManager(), _jspx_th_vgcutil_005fmessage_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_vgcutil_005fmessage_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  vgcutil:message
    com.visiongc.commons.struts.tag.MessageTag _jspx_th_vgcutil_005fmessage_005f4 = (com.visiongc.commons.struts.tag.MessageTag) _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.get(com.visiongc.commons.struts.tag.MessageTag.class);
    boolean _jspx_th_vgcutil_005fmessage_005f4_reused = false;
    try {
      _jspx_th_vgcutil_005fmessage_005f4.setPageContext(_jspx_page_context);
      _jspx_th_vgcutil_005fmessage_005f4.setParent(null);
      // /index.jsp(50,435) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_vgcutil_005fmessage_005f4.setKey("aplicacion.acronimo");
      int _jspx_eval_vgcutil_005fmessage_005f4 = _jspx_th_vgcutil_005fmessage_005f4.doStartTag();
      if (_jspx_th_vgcutil_005fmessage_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_vgcutil_005fmessage_005f4);
      _jspx_th_vgcutil_005fmessage_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_vgcutil_005fmessage_005f4, _jsp_getInstanceManager(), _jspx_th_vgcutil_005fmessage_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005frewrite_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:rewrite
    org.apache.struts.taglib.html.RewriteTag _jspx_th_html_005frewrite_005f2 = (org.apache.struts.taglib.html.RewriteTag) _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005faction_005fnobody.get(org.apache.struts.taglib.html.RewriteTag.class);
    boolean _jspx_th_html_005frewrite_005f2_reused = false;
    try {
      _jspx_th_html_005frewrite_005f2.setPageContext(_jspx_page_context);
      _jspx_th_html_005frewrite_005f2.setParent(null);
      // /index.jsp(57,58) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005frewrite_005f2.setAction("/logout");
      int _jspx_eval_html_005frewrite_005f2 = _jspx_th_html_005frewrite_005f2.doStartTag();
      if (_jspx_th_html_005frewrite_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005faction_005fnobody.reuse(_jspx_th_html_005frewrite_005f2);
      _jspx_th_html_005frewrite_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005frewrite_005f2, _jsp_getInstanceManager(), _jspx_th_html_005frewrite_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005frewrite_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:rewrite
    org.apache.struts.taglib.html.RewriteTag _jspx_th_html_005frewrite_005f3 = (org.apache.struts.taglib.html.RewriteTag) _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005faction_005fnobody.get(org.apache.struts.taglib.html.RewriteTag.class);
    boolean _jspx_th_html_005frewrite_005f3_reused = false;
    try {
      _jspx_th_html_005frewrite_005f3.setPageContext(_jspx_page_context);
      _jspx_th_html_005frewrite_005f3.setParent(null);
      // /index.jsp(58,36) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005frewrite_005f3.setAction("/logout");
      int _jspx_eval_html_005frewrite_005f3 = _jspx_th_html_005frewrite_005f3.doStartTag();
      if (_jspx_th_html_005frewrite_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005faction_005fnobody.reuse(_jspx_th_html_005frewrite_005f3);
      _jspx_th_html_005frewrite_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005frewrite_005f3, _jsp_getInstanceManager(), _jspx_th_html_005frewrite_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_vgcutil_005fmessage_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  vgcutil:message
    com.visiongc.commons.struts.tag.MessageTag _jspx_th_vgcutil_005fmessage_005f5 = (com.visiongc.commons.struts.tag.MessageTag) _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.get(com.visiongc.commons.struts.tag.MessageTag.class);
    boolean _jspx_th_vgcutil_005fmessage_005f5_reused = false;
    try {
      _jspx_th_vgcutil_005fmessage_005f5.setPageContext(_jspx_page_context);
      _jspx_th_vgcutil_005fmessage_005f5.setParent(null);
      // /index.jsp(84,12) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_vgcutil_005fmessage_005f5.setKey("jsp.index.funcionNoPermitida");
      int _jspx_eval_vgcutil_005fmessage_005f5 = _jspx_th_vgcutil_005fmessage_005f5.doStartTag();
      if (_jspx_th_vgcutil_005fmessage_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_vgcutil_005fmessage_005f5);
      _jspx_th_vgcutil_005fmessage_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_vgcutil_005fmessage_005f5, _jsp_getInstanceManager(), _jspx_th_vgcutil_005fmessage_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_vgcutil_005fmessage_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  vgcutil:message
    com.visiongc.commons.struts.tag.MessageTag _jspx_th_vgcutil_005fmessage_005f6 = (com.visiongc.commons.struts.tag.MessageTag) _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.get(com.visiongc.commons.struts.tag.MessageTag.class);
    boolean _jspx_th_vgcutil_005fmessage_005f6_reused = false;
    try {
      _jspx_th_vgcutil_005fmessage_005f6.setPageContext(_jspx_page_context);
      _jspx_th_vgcutil_005fmessage_005f6.setParent(null);
      // /index.jsp(145,14) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_vgcutil_005fmessage_005f6.setKey("jsp.index.funcionNoPermitida");
      int _jspx_eval_vgcutil_005fmessage_005f6 = _jspx_th_vgcutil_005fmessage_005f6.doStartTag();
      if (_jspx_th_vgcutil_005fmessage_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_vgcutil_005fmessage_005f6);
      _jspx_th_vgcutil_005fmessage_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_vgcutil_005fmessage_005f6, _jsp_getInstanceManager(), _jspx_th_vgcutil_005fmessage_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005frewrite_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:rewrite
    org.apache.struts.taglib.html.RewriteTag _jspx_th_html_005frewrite_005f4 = (org.apache.struts.taglib.html.RewriteTag) _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.get(org.apache.struts.taglib.html.RewriteTag.class);
    boolean _jspx_th_html_005frewrite_005f4_reused = false;
    try {
      _jspx_th_html_005frewrite_005f4.setPageContext(_jspx_page_context);
      _jspx_th_html_005frewrite_005f4.setParent(null);
      // /index.jsp(165,18) name = page type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005frewrite_005f4.setPage("/componentes/comunes/vineta.gif");
      int _jspx_eval_html_005frewrite_005f4 = _jspx_th_html_005frewrite_005f4.doStartTag();
      if (_jspx_th_html_005frewrite_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.reuse(_jspx_th_html_005frewrite_005f4);
      _jspx_th_html_005frewrite_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005frewrite_005f4, _jsp_getInstanceManager(), _jspx_th_html_005frewrite_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_vgcutil_005fmessage_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  vgcutil:message
    com.visiongc.commons.struts.tag.MessageTag _jspx_th_vgcutil_005fmessage_005f7 = (com.visiongc.commons.struts.tag.MessageTag) _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.get(com.visiongc.commons.struts.tag.MessageTag.class);
    boolean _jspx_th_vgcutil_005fmessage_005f7_reused = false;
    try {
      _jspx_th_vgcutil_005fmessage_005f7.setPageContext(_jspx_page_context);
      _jspx_th_vgcutil_005fmessage_005f7.setParent(null);
      // /index.jsp(165,303) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_vgcutil_005fmessage_005f7.setKey("jsp.index.bienvenida");
      int _jspx_eval_vgcutil_005fmessage_005f7 = _jspx_th_vgcutil_005fmessage_005f7.doStartTag();
      if (_jspx_th_vgcutil_005fmessage_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_vgcutil_005fmessage_005f7);
      _jspx_th_vgcutil_005fmessage_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_vgcutil_005fmessage_005f7, _jsp_getInstanceManager(), _jspx_th_vgcutil_005fmessage_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_vgcutil_005fmessage_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  vgcutil:message
    com.visiongc.commons.struts.tag.MessageTag _jspx_th_vgcutil_005fmessage_005f8 = (com.visiongc.commons.struts.tag.MessageTag) _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.get(com.visiongc.commons.struts.tag.MessageTag.class);
    boolean _jspx_th_vgcutil_005fmessage_005f8_reused = false;
    try {
      _jspx_th_vgcutil_005fmessage_005f8.setPageContext(_jspx_page_context);
      _jspx_th_vgcutil_005fmessage_005f8.setParent(null);
      // /index.jsp(165,350) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_vgcutil_005fmessage_005f8.setKey("aplicacion.nombre");
      int _jspx_eval_vgcutil_005fmessage_005f8 = _jspx_th_vgcutil_005fmessage_005f8.doStartTag();
      if (_jspx_th_vgcutil_005fmessage_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_vgcutil_005fmessage_005f8);
      _jspx_th_vgcutil_005fmessage_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_vgcutil_005fmessage_005f8, _jsp_getInstanceManager(), _jspx_th_vgcutil_005fmessage_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_vgcutil_005fmessage_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  vgcutil:message
    com.visiongc.commons.struts.tag.MessageTag _jspx_th_vgcutil_005fmessage_005f9 = (com.visiongc.commons.struts.tag.MessageTag) _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.get(com.visiongc.commons.struts.tag.MessageTag.class);
    boolean _jspx_th_vgcutil_005fmessage_005f9_reused = false;
    try {
      _jspx_th_vgcutil_005fmessage_005f9.setPageContext(_jspx_page_context);
      _jspx_th_vgcutil_005fmessage_005f9.setParent(null);
      // /index.jsp(165,394) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_vgcutil_005fmessage_005f9.setKey("aplicacion.version");
      int _jspx_eval_vgcutil_005fmessage_005f9 = _jspx_th_vgcutil_005fmessage_005f9.doStartTag();
      if (_jspx_th_vgcutil_005fmessage_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_vgcutil_005fmessage_005f9);
      _jspx_th_vgcutil_005fmessage_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_vgcutil_005fmessage_005f9, _jsp_getInstanceManager(), _jspx_th_vgcutil_005fmessage_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_vgcutil_005fmessage_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  vgcutil:message
    com.visiongc.commons.struts.tag.MessageTag _jspx_th_vgcutil_005fmessage_005f10 = (com.visiongc.commons.struts.tag.MessageTag) _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.get(com.visiongc.commons.struts.tag.MessageTag.class);
    boolean _jspx_th_vgcutil_005fmessage_005f10_reused = false;
    try {
      _jspx_th_vgcutil_005fmessage_005f10.setPageContext(_jspx_page_context);
      _jspx_th_vgcutil_005fmessage_005f10.setParent(null);
      // /index.jsp(165,439) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_vgcutil_005fmessage_005f10.setKey("aplicacion.version.text.build");
      int _jspx_eval_vgcutil_005fmessage_005f10 = _jspx_th_vgcutil_005fmessage_005f10.doStartTag();
      if (_jspx_th_vgcutil_005fmessage_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_vgcutil_005fmessage_005f10);
      _jspx_th_vgcutil_005fmessage_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_vgcutil_005fmessage_005f10, _jsp_getInstanceManager(), _jspx_th_vgcutil_005fmessage_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_vgcutil_005fmessage_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  vgcutil:message
    com.visiongc.commons.struts.tag.MessageTag _jspx_th_vgcutil_005fmessage_005f11 = (com.visiongc.commons.struts.tag.MessageTag) _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.get(com.visiongc.commons.struts.tag.MessageTag.class);
    boolean _jspx_th_vgcutil_005fmessage_005f11_reused = false;
    try {
      _jspx_th_vgcutil_005fmessage_005f11.setPageContext(_jspx_page_context);
      _jspx_th_vgcutil_005fmessage_005f11.setParent(null);
      // /index.jsp(165,495) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_vgcutil_005fmessage_005f11.setKey("aplicacion.version.build");
      int _jspx_eval_vgcutil_005fmessage_005f11 = _jspx_th_vgcutil_005fmessage_005f11.doStartTag();
      if (_jspx_th_vgcutil_005fmessage_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_vgcutil_005fmessage_005f11);
      _jspx_th_vgcutil_005fmessage_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_vgcutil_005fmessage_005f11, _jsp_getInstanceManager(), _jspx_th_vgcutil_005fmessage_005f11_reused);
    }
    return false;
  }
}
