/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2022-03-30 15:34:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.componentes.visorLista;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class visorListaJs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/tld/vgc-util.tld", Long.valueOf(1646829839000L));
    _jspx_dependants.put("/WEB-INF/tld/struts-html.tld", Long.valueOf(1646829839000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.release();
    _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"/paginas/comunes/errorJsp.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Creado por: Kerwin Arias (05/03/2012) -->\n");
      out.write("<!-- Modificado por: Kerwin Arias (27/08/2012) -->\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("\tfunction consultar(forma, inOrden, inPagina) \n");
      out.write("\t{\n");
      out.write("\t\tif (typeof(forma.seleccionados) != \"undefined\")\n");
      out.write("\t\t\tforma.seleccionados.value = \"\";\n");
      out.write("\n");
      out.write("\t\tif (inPagina != null) \n");
      out.write("\t\t{\n");
      out.write("\t\t\tforma.pagina.value=inPagina;\n");
      out.write("\t\t\tforma.submit();\n");
      out.write("\t\t}\t\n");
      out.write("\t\n");
      out.write("\t\tif (inOrden != null) \n");
      out.write("\t\t{\n");
      out.write("\t\t\tvar cambioOrden = (forma.atributoOrden.value != inOrden);\n");
      out.write("\t\t\tforma.atributoOrden.value=inOrden;\n");
      out.write("\t\t\tif (cambioOrden) \n");
      out.write("\t\t\t\tforma.tipoOrden.value = 'ASC';\t\t\t\n");
      out.write("\t\t\telse \n");
      out.write("\t\t\t{\n");
      out.write("\t\t\t\tif (forma.tipoOrden.value != null) \n");
      out.write("\t\t\t\t{\n");
      out.write("\t\t\t\t\tif (forma.tipoOrden.value == 'ASC') \n");
      out.write("\t\t\t\t\t\tforma.tipoOrden.value = 'DESC';\t\t\t\t\t\n");
      out.write("\t\t\t\t\telse \n");
      out.write("\t\t\t\t\t\tforma.tipoOrden.value = 'ASC';\t\t\t\t\t\n");
      out.write("\t\t\t\t} \n");
      out.write("\t\t\t\telse \n");
      out.write("\t\t\t\t\tforma.tipoOrden.value = 'ASC';\t\t\t\t\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\n");
      out.write("\t\tforma.submit();\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// Modificado por: Kerwin Arias (27/08/2012)\n");
      out.write("\tfunction cambioImagenOrden(forma) \n");
      out.write("\t{\n");
      out.write("\t\tif ((forma.atributoOrden.value != null) && (forma.atributoOrden.value != '')) \n");
      out.write("\t\t{\n");
      out.write("\t\t\turl = \"");
      if (_jspx_meth_html_005frewrite_005f0(_jspx_page_context))
        return;
      out.write("\";\n");
      out.write("\t\t\t// Hace las validaciones correspondientes y dibuja las imagen\n");
      out.write("\t\t\tif (forma.tipoOrden.value == \"ASC\") \n");
      out.write("\t\t\t\tdocument.images[forma.atributoOrden.value].src = url + \"componentes/visorLista/arriba.gif\";\n");
      out.write("\t\t\telse if (forma.tipoOrden.value == \"DESC\") \n");
      out.write("\t\t\t\tdocument.images[forma.atributoOrden.value].src = url + \"componentes/visorLista/abajo.gif\";\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction verificarObjetoSeleccionado(my_form, form_field, errorMsg, my_action, confirmMsg, multiSelect, errorSimpleSelect) \n");
      out.write("\t{\n");
      out.write("\t\tvar length = my_form.elements.length;\n");
      out.write("\t\tvar index = 0;\n");
      out.write("\t\tvar checked = 0;\n");
      out.write("\t\tvar totalSelected = 0;\n");
      out.write("\t\t\n");
      out.write("\t\tfor( index=0; index < length; index++ ) \n");
      out.write("\t\t{\n");
      out.write("\t\t\tif( my_form.elements[index].name == form_field && my_form.elements[index].checked  ) \n");
      out.write("\t\t\t{\n");
      out.write("\t\t\t\tchecked = 1;\n");
      out.write("\t\t\t\ttotalSelected++;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tif ( !checked ) \n");
      out.write("\t\t\talert(errorMsg);\n");
      out.write("\t\telse \n");
      out.write("\t\t{\n");
      out.write("\t\t\tif ((!multiSelect) && (totalSelected>1)) \n");
      out.write("\t\t\t{\n");
      out.write("\t\t\t\talert(errorSimpleSelect);\n");
      out.write("\t\t\t\treturn;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tres = false;\n");
      out.write("\t\t\tif (confirmMsg.length > 0) \n");
      out.write("\t\t\t\tres = confirm(confirmMsg);\n");
      out.write("\t\t\telse \n");
      out.write("\t\t\t\tres = true;\n");
      out.write("\t\t\tif (res) \n");
      out.write("\t\t\t{\n");
      out.write("\t\t\t\tmy_form.action = my_action;\n");
      out.write("\t\t\t\tmy_form.submit();\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// Creado por: Kerwin Arias (05/03/2012)\n");
      out.write("\tfunction eventoMouseFueraFila(forma, fila) \n");
      out.write("\t{\n");
      out.write("\t\tif (forma.seleccionados.value != fila.id) \n");
      out.write("\t\t\tfila.className='mouseFueraCuerpoListView';\n");
      out.write("\t\telse \n");
      out.write("\t\t\tfila.className='cuerpoListViewFilaSeleccionada';\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// Creado por: Kerwin Arias (05/03/2012)\n");
      out.write("\tfunction eventoMouseEncimaFila(forma, fila) \n");
      out.write("\t{\n");
      out.write("\t\tif (forma.seleccionados.value != fila.id) \n");
      out.write("\t\t\tfila.className='mouseEncimaCuerpoListView';\n");
      out.write("\t\telse \n");
      out.write("\t\t\tfila.className='cuerpoListViewFilaSeleccionada';\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// Creado por: Kerwin Arias (05/03/2012)\n");
      out.write("\tfunction eventoClickFila(forma, idTabla, fila) \n");
      out.write("\t{\n");
      out.write("\t\tif (forma.seleccionados.value != fila.id) \n");
      out.write("\t\t{\n");
      out.write("\t\t\tforma.seleccionados.value = fila.id;\n");
      out.write("\t\t\tvar objeto = document.getElementById('valor' + fila.id);\n");
      out.write("\t\t\tif (objeto != null) \n");
      out.write("\t\t\t{\n");
      out.write("\t\t\t\tvar valor = objeto.innerHTML;\n");
      out.write("\t\t\t\tif (forma.valoresSeleccionados != null) \n");
      out.write("\t\t\t\t\tforma.valoresSeleccionados.value = valor;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t} \n");
      out.write("\t\telse \n");
      out.write("\t\t{\n");
      out.write("\t\t\tif (forma.valoresSeleccionados != null) \n");
      out.write("\t\t\t\tforma.seleccionados.value = '';\n");
      out.write("\t\t}\n");
      out.write("\t\tactualizarSeleccionados(forma, idTabla);\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction actualizarSeleccionados(forma, idTabla) \n");
      out.write("\t{\n");
      out.write("\t\tvar tabla = document.getElementById(idTabla);\n");
      out.write("\t\tvar i = 0;\n");
      out.write("\t\tfor (i = 1; i < tabla.rows.length; i++) \n");
      out.write("\t\t{\n");
      out.write("\t\t\tvar fila = tabla.rows[i];\n");
      out.write("\t\t\teventoMouseEncimaFila(forma, fila);\n");
      out.write("\t\t\teventoMouseFueraFila(forma, fila);\n");
      out.write("\t\t\tsetImagenSeleccionadoFila(forma, fila);\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction setImagenSeleccionadoFila(forma, fila) \n");
      out.write("\t{\n");
      out.write("\t\t// Hace las validaciones correspondientes y dibuja las imagen\n");
      out.write("\t\turl = \"");
      if (_jspx_meth_html_005frewrite_005f1(_jspx_page_context))
        return;
      out.write("\";\n");
      out.write("\t\tif (document.images['img' + fila.id] != null) \n");
      out.write("\t\t{\n");
      out.write("\t\t\tif (forma.seleccionados.value.indexOf(fila.id) == -1) \n");
      out.write("\t\t\t\tdocument.images['img' + fila.id].src = url + \"componentes/visorLista/transparente.gif\";\n");
      out.write("\t\t\telse \n");
      out.write("\t\t\t{\n");
      out.write("\t\t\t\tdocument.images['img' + fila.id].src = url + \"componentes/visorLista/seleccionado.gif\";\n");
      out.write("\t\t\t\tdocument.images['img' + fila.id].title = '");
      if (_jspx_meth_vgcutil_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("';\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// Creado por: Kerwin Arias (18/06/2012)\n");
      out.write("\tfunction consultarV2(forma, campoPagina, campoAtributoOrden, campoTipoOrden, inOrden, inPagina) \n");
      out.write("\t{\n");
      out.write("\t\tif (typeof(forma.seleccionados) != \"undefined\")\n");
      out.write("\t\t\tforma.seleccionados.value = \"\";\n");
      out.write("\n");
      out.write("\t\tif (inPagina != null) \n");
      out.write("\t\t{\n");
      out.write("\t\t\tcampoPagina.value = inPagina;\n");
      out.write("\t\t\tforma.submit();\n");
      out.write("\t\t}\n");
      out.write("\t\n");
      out.write("\t\tif (inOrden != null) \n");
      out.write("\t\t{\n");
      out.write("\t\t\tvar cambioOrden = (campoAtributoOrden.value != inOrden);\n");
      out.write("\t\t\tcampoAtributoOrden.value=inOrden;\n");
      out.write("\t\t\tif (cambioOrden) \n");
      out.write("\t\t\t\tcampoTipoOrden.value = 'ASC';\t\t\t\n");
      out.write("\t\t\telse \n");
      out.write("\t\t\t{\n");
      out.write("\t\t\t\tif (campoTipoOrden.value != null) \n");
      out.write("\t\t\t\t{\n");
      out.write("\t\t\t\t\tif (campoTipoOrden.value == 'ASC') \n");
      out.write("\t\t\t\t\t\tcampoTipoOrden.value = 'DESC';\t\t\t\t\t\n");
      out.write("\t\t\t\t\telse \n");
      out.write("\t\t\t\t\t\tcampoTipoOrden.value = 'ASC';\t\t\t\t\t\n");
      out.write("\t\t\t\t} \n");
      out.write("\t\t\t\telse \n");
      out.write("\t\t\t\t\tcampoTipoOrden.value = 'ASC';\t\t\t\t\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\n");
      out.write("\t\tforma.submit();\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// Creado por: Kerwin Arias (27/08/2012)\n");
      out.write("\tfunction cambioImagenOrdenV2(campoAtributoOrden, campoTipoOrden) \n");
      out.write("\t{\n");
      out.write("\t\tif ((campoAtributoOrden.value != null) && (campoAtributoOrden.value != '')) \n");
      out.write("\t\t{\n");
      out.write("\t\t\turl = \"");
      if (_jspx_meth_html_005frewrite_005f2(_jspx_page_context))
        return;
      out.write("\";\n");
      out.write("\t\t\t// Hace las validaciones correspondientes y dibuja las imagen\n");
      out.write("\t\t\tif (campoTipoOrden.value == \"ASC\") \n");
      out.write("\t\t\t\tdocument.images[campoAtributoOrden.value].src = url + \"componentes/visorLista/arriba.gif\";\n");
      out.write("\t\t\telse if (campoTipoOrden.value == \"DESC\") \n");
      out.write("\t\t\t\tdocument.images[campoAtributoOrden.value].src = url + \"componentes/visorLista/abajo.gif\";\t\t\t\t\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// Creado por: Kerwin Arias (18/06/2012)\n");
      out.write("\tfunction eventoClickFilaV2(campoIdSeleccionado, campoValorSeleccionado, idTabla, fila) \n");
      out.write("\t{\n");
      out.write("\t\tvar buscado = fila.id;\n");
      out.write("\t\tif (campoIdSeleccionado.value != buscado) \n");
      out.write("\t\t{\n");
      out.write("\t\t\tcampoIdSeleccionado.value = buscado;\n");
      out.write("\t\t\tvar objeto = document.getElementById('valor' + buscado);\n");
      out.write("\t\t\tif (objeto != null) \n");
      out.write("\t\t\t{\n");
      out.write("\t\t\t\tvar valor = objeto.innerHTML;\n");
      out.write("\t\t\t\tif (campoValorSeleccionado != null) \n");
      out.write("\t\t\t\t\tcampoValorSeleccionado.value = valor;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tactualizarSeleccionadosV2(campoIdSeleccionado, idTabla);\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// Creado por: Kerwin Arias (18/06/2012)\n");
      out.write("\tfunction actualizarSeleccionadosV2(campoIdSeleccionado, idTabla) \n");
      out.write("\t{\n");
      out.write("\t\tvar tabla = document.getElementById(idTabla);\n");
      out.write("\t\tvar i = 0;\n");
      out.write("\t\tfor (i = 1; i < tabla.rows.length; i++) \n");
      out.write("\t\t{\n");
      out.write("\t\t\tvar fila = tabla.rows[i];\n");
      out.write("\t\t\teventoMouseEncimaFilaV2(campoIdSeleccionado, fila);\n");
      out.write("\t\t\teventoMouseFueraFilaV2(campoIdSeleccionado, fila);\n");
      out.write("\t\t\tsetImagenSeleccionadoFilaV2(campoIdSeleccionado, fila);\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// Creado por: Kerwin Arias (18/06/2012)\n");
      out.write("\tfunction eventoMouseFueraFilaV2(campoIdSeleccionado, fila) \n");
      out.write("\t{\n");
      out.write("\t\tif (campoIdSeleccionado.value != fila.id) \n");
      out.write("\t\t\tfila.className='mouseFueraCuerpoListView';\n");
      out.write("\t\telse \n");
      out.write("\t\t\tfila.className='cuerpoListViewFilaSeleccionada';\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// Creado por: Kerwin Arias (18/06/2012)\n");
      out.write("\tfunction eventoMouseEncimaFilaV2(campoIdSeleccionado, fila) \n");
      out.write("\t{\n");
      out.write("\t\tif (campoIdSeleccionado.value != fila.id) \n");
      out.write("\t\t\tfila.className='mouseEncimaCuerpoListView';\n");
      out.write("\t\telse \n");
      out.write("\t\t\tfila.className='cuerpoListViewFilaSeleccionada';\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// Creado por: Kerwin Arias (18/06/2012)\n");
      out.write("\tfunction setImagenSeleccionadoFilaV2(campoIdSeleccionado, fila) \n");
      out.write("\t{\n");
      out.write("\t\t// Hace las validaciones correspondientes y dibuja las imagen\n");
      out.write("\t\turl = \"");
      if (_jspx_meth_html_005frewrite_005f3(_jspx_page_context))
        return;
      out.write("\";\n");
      out.write("\t\tif (document.images['img' + fila.id] != null) \n");
      out.write("\t\t{\n");
      out.write("\t\t\tif (campoIdSeleccionado.value != fila.id) \n");
      out.write("\t\t\t\tdocument.images['img' + fila.id].src = url + \"componentes/visorLista/transparente.gif\";\n");
      out.write("\t\t\telse \n");
      out.write("\t\t\t{\n");
      out.write("\t\t\t\tdocument.images['img' + fila.id].src = url + \"componentes/visorLista/seleccionado.gif\";\n");
      out.write("\t\t\t\tdocument.images['img' + fila.id].title = '");
      if (_jspx_meth_vgcutil_005fmessage_005f1(_jspx_page_context))
        return;
      out.write("';\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction inicializarVisorListaSeleccionSimple(campoIdSeleccionado, idTabla) \n");
      out.write("\t{\n");
      out.write("\t\tactualizarSeleccionadosV2(campoIdSeleccionado, idTabla);\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// Funcion que selecciona/deselecciona todos los elementos de un\n");
      out.write("\t// visor de lista\n");
      out.write("\t// Creado por: Kerwin Arias (06/06/2012)\n");
      out.write("\tfunction selectUnselectAllObject(forma, campoControl, nombreCampo) \n");
      out.write("\t{\n");
      out.write("\t\tvar flag;\n");
      out.write("\t\tif (campoControl.checked) \n");
      out.write("\t\t\tflag = true;\n");
      out.write("\t\telse \n");
      out.write("\t\t\tflag = false;\n");
      out.write("\t\n");
      out.write("\t\tlen=forma.elements.length;\n");
      out.write("\t\tvar index=0;\n");
      out.write("\t\tfor( index=0; index < len; index++ ) \n");
      out.write("\t\t{\n");
      out.write("\t\t\tif(forma.elements[index].name == nombreCampo) \n");
      out.write("\t\t\t\tforma.elements[index].checked=flag;\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// Creado por: Kerwin Arias (27/08/2012)\n");
      out.write("\tfunction consultarConfigurable(forma, action, campoPagina, campoAtributoOrden, campoTipoOrden, inOrden, inPagina) \n");
      out.write("\t{\n");
      out.write("\t\tif (action != null) \n");
      out.write("\t\t\tforma.action = action;\n");
      out.write("\t\tif (inPagina != null) \n");
      out.write("\t\t{\n");
      out.write("\t\t\tcampoPagina.value = inPagina;\n");
      out.write("\t\t\tforma.submit();\n");
      out.write("\t\t}\n");
      out.write("\t\n");
      out.write("\t\tif (inOrden != null) \n");
      out.write("\t\t{\n");
      out.write("\t\t\tvar cambioOrden = (campoAtributoOrden.value != inOrden);\n");
      out.write("\t\t\tcampoAtributoOrden.value=inOrden;\n");
      out.write("\t\t\tif (cambioOrden) \n");
      out.write("\t\t\t\tcampoTipoOrden.value = 'ASC';\t\t\t\n");
      out.write("\t\t\telse \n");
      out.write("\t\t\t{\n");
      out.write("\t\t\t\tif (campoTipoOrden.value != null) \n");
      out.write("\t\t\t\t{\n");
      out.write("\t\t\t\t\tif (campoTipoOrden.value == 'ASC') \n");
      out.write("\t\t\t\t\t\tcampoTipoOrden.value = 'DESC';\t\t\t\t\t\n");
      out.write("\t\t\t\t\telse \n");
      out.write("\t\t\t\t\t\tcampoTipoOrden.value = 'ASC';\t\t\t\t\t\n");
      out.write("\t\t\t\t} \n");
      out.write("\t\t\t\telse \n");
      out.write("\t\t\t\t\tcampoTipoOrden.value = 'ASC';\t\t\t\t\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\n");
      out.write("\t\tforma.submit();\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// Creado por: Kerwin Arias (08/09/2012)\n");
      out.write("\tfunction cambioImagenOrdenV3(campoAtributoOrden, campoTipoOrden, nombreVisorLista) \n");
      out.write("\t{\n");
      out.write("\t\tif ((campoAtributoOrden.value != null) && (campoAtributoOrden.value != '')) \n");
      out.write("\t\t{\n");
      out.write("\t\t\turl = \"");
      if (_jspx_meth_html_005frewrite_005f4(_jspx_page_context))
        return;
      out.write("\";\n");
      out.write("\t\t\t// Hace las validaciones correspondientes y dibuja las imagen\n");
      out.write("\t\t\tif (campoTipoOrden.value == \"ASC\") \n");
      out.write("\t\t\t\tdocument.images[nombreVisorLista + campoAtributoOrden.value].src = url + \"componentes/visorLista/arriba.gif\";\n");
      out.write("\t\t\telse if (campoTipoOrden.value == \"DESC\") \n");
      out.write("\t\t\t\tdocument.images[nombreVisorLista + campoAtributoOrden.value].src = url + \"componentes/visorLista/abajo.gif\";\t\t\t\t\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("</script>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_html_005frewrite_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:rewrite
    org.apache.struts.taglib.html.RewriteTag _jspx_th_html_005frewrite_005f0 = (org.apache.struts.taglib.html.RewriteTag) _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.get(org.apache.struts.taglib.html.RewriteTag.class);
    boolean _jspx_th_html_005frewrite_005f0_reused = false;
    try {
      _jspx_th_html_005frewrite_005f0.setPageContext(_jspx_page_context);
      _jspx_th_html_005frewrite_005f0.setParent(null);
      // /componentes/visorLista/visorListaJs.jsp(50,10) name = page type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005frewrite_005f0.setPage("/");
      int _jspx_eval_html_005frewrite_005f0 = _jspx_th_html_005frewrite_005f0.doStartTag();
      if (_jspx_th_html_005frewrite_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.reuse(_jspx_th_html_005frewrite_005f0);
      _jspx_th_html_005frewrite_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005frewrite_005f0, _jsp_getInstanceManager(), _jspx_th_html_005frewrite_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005frewrite_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:rewrite
    org.apache.struts.taglib.html.RewriteTag _jspx_th_html_005frewrite_005f1 = (org.apache.struts.taglib.html.RewriteTag) _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.get(org.apache.struts.taglib.html.RewriteTag.class);
    boolean _jspx_th_html_005frewrite_005f1_reused = false;
    try {
      _jspx_th_html_005frewrite_005f1.setPageContext(_jspx_page_context);
      _jspx_th_html_005frewrite_005f1.setParent(null);
      // /componentes/visorLista/visorListaJs.jsp(153,9) name = page type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005frewrite_005f1.setPage("/");
      int _jspx_eval_html_005frewrite_005f1 = _jspx_th_html_005frewrite_005f1.doStartTag();
      if (_jspx_th_html_005frewrite_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.reuse(_jspx_th_html_005frewrite_005f1);
      _jspx_th_html_005frewrite_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005frewrite_005f1, _jsp_getInstanceManager(), _jspx_th_html_005frewrite_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_vgcutil_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  vgcutil:message
    com.visiongc.commons.struts.tag.MessageTag _jspx_th_vgcutil_005fmessage_005f0 = (com.visiongc.commons.struts.tag.MessageTag) _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.get(com.visiongc.commons.struts.tag.MessageTag.class);
    boolean _jspx_th_vgcutil_005fmessage_005f0_reused = false;
    try {
      _jspx_th_vgcutil_005fmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_vgcutil_005fmessage_005f0.setParent(null);
      // /componentes/visorLista/visorListaJs.jsp(161,46) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_vgcutil_005fmessage_005f0.setKey("commons.seleccionado");
      int _jspx_eval_vgcutil_005fmessage_005f0 = _jspx_th_vgcutil_005fmessage_005f0.doStartTag();
      if (_jspx_th_vgcutil_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_vgcutil_005fmessage_005f0);
      _jspx_th_vgcutil_005fmessage_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_vgcutil_005fmessage_005f0, _jsp_getInstanceManager(), _jspx_th_vgcutil_005fmessage_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005frewrite_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:rewrite
    org.apache.struts.taglib.html.RewriteTag _jspx_th_html_005frewrite_005f2 = (org.apache.struts.taglib.html.RewriteTag) _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.get(org.apache.struts.taglib.html.RewriteTag.class);
    boolean _jspx_th_html_005frewrite_005f2_reused = false;
    try {
      _jspx_th_html_005frewrite_005f2.setPageContext(_jspx_page_context);
      _jspx_th_html_005frewrite_005f2.setParent(null);
      // /componentes/visorLista/visorListaJs.jsp(206,10) name = page type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005frewrite_005f2.setPage("/");
      int _jspx_eval_html_005frewrite_005f2 = _jspx_th_html_005frewrite_005f2.doStartTag();
      if (_jspx_th_html_005frewrite_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.reuse(_jspx_th_html_005frewrite_005f2);
      _jspx_th_html_005frewrite_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005frewrite_005f2, _jsp_getInstanceManager(), _jspx_th_html_005frewrite_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005frewrite_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:rewrite
    org.apache.struts.taglib.html.RewriteTag _jspx_th_html_005frewrite_005f3 = (org.apache.struts.taglib.html.RewriteTag) _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.get(org.apache.struts.taglib.html.RewriteTag.class);
    boolean _jspx_th_html_005frewrite_005f3_reused = false;
    try {
      _jspx_th_html_005frewrite_005f3.setPageContext(_jspx_page_context);
      _jspx_th_html_005frewrite_005f3.setParent(null);
      // /componentes/visorLista/visorListaJs.jsp(270,9) name = page type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005frewrite_005f3.setPage("/");
      int _jspx_eval_html_005frewrite_005f3 = _jspx_th_html_005frewrite_005f3.doStartTag();
      if (_jspx_th_html_005frewrite_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.reuse(_jspx_th_html_005frewrite_005f3);
      _jspx_th_html_005frewrite_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005frewrite_005f3, _jsp_getInstanceManager(), _jspx_th_html_005frewrite_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_vgcutil_005fmessage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  vgcutil:message
    com.visiongc.commons.struts.tag.MessageTag _jspx_th_vgcutil_005fmessage_005f1 = (com.visiongc.commons.struts.tag.MessageTag) _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.get(com.visiongc.commons.struts.tag.MessageTag.class);
    boolean _jspx_th_vgcutil_005fmessage_005f1_reused = false;
    try {
      _jspx_th_vgcutil_005fmessage_005f1.setPageContext(_jspx_page_context);
      _jspx_th_vgcutil_005fmessage_005f1.setParent(null);
      // /componentes/visorLista/visorListaJs.jsp(278,46) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_vgcutil_005fmessage_005f1.setKey("commons.seleccionado");
      int _jspx_eval_vgcutil_005fmessage_005f1 = _jspx_th_vgcutil_005fmessage_005f1.doStartTag();
      if (_jspx_th_vgcutil_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_vgcutil_005fmessage_005f1);
      _jspx_th_vgcutil_005fmessage_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_vgcutil_005fmessage_005f1, _jsp_getInstanceManager(), _jspx_th_vgcutil_005fmessage_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005frewrite_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:rewrite
    org.apache.struts.taglib.html.RewriteTag _jspx_th_html_005frewrite_005f4 = (org.apache.struts.taglib.html.RewriteTag) _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.get(org.apache.struts.taglib.html.RewriteTag.class);
    boolean _jspx_th_html_005frewrite_005f4_reused = false;
    try {
      _jspx_th_html_005frewrite_005f4.setPageContext(_jspx_page_context);
      _jspx_th_html_005frewrite_005f4.setParent(null);
      // /componentes/visorLista/visorListaJs.jsp(347,10) name = page type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005frewrite_005f4.setPage("/");
      int _jspx_eval_html_005frewrite_005f4 = _jspx_th_html_005frewrite_005f4.doStartTag();
      if (_jspx_th_html_005frewrite_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.reuse(_jspx_th_html_005frewrite_005f4);
      _jspx_th_html_005frewrite_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005frewrite_005f4, _jsp_getInstanceManager(), _jspx_th_html_005frewrite_005f4_reused);
    }
    return false;
  }
}
