/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2022-08-01 22:55:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.componentes.visorLista;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class visorListaJsTag_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/tld/vgc-util.tld", Long.valueOf(1646829840000L));
    _jspx_dependants.put("/WEB-INF/tld/struts-html.tld", Long.valueOf(1646829840000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.release();
    _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"/paginas/comunes/errorJsp.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Creado por: Kerwin Arias (05/03/2012) -->\n");
      out.write("<!-- Modificado por: Kerwin Arias (17/09/2012) -->\n");
      out.write("\n");
      out.write("//<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("	function consultar(forma, inOrden, inPagina) \n");
      out.write("	{\n");
      out.write("		if (typeof(forma.seleccionados) != \"undefined\")\n");
      out.write("			forma.seleccionados.value = \"\";\n");
      out.write("	\n");
      out.write("		if (inPagina != null) \n");
      out.write("		{\n");
      out.write("			forma.pagina.value=inPagina;\n");
      out.write("			forma.submit();\n");
      out.write("		}	\n");
      out.write("	\n");
      out.write("		if (inOrden != null) \n");
      out.write("		{\n");
      out.write("			var cambioOrden = (forma.atributoOrden.value != inOrden);\n");
      out.write("			forma.atributoOrden.value=inOrden;\n");
      out.write("			if (cambioOrden) \n");
      out.write("				forma.tipoOrden.value = 'ASC';			\n");
      out.write("			else \n");
      out.write("			{\n");
      out.write("				if (forma.tipoOrden.value != null) \n");
      out.write("				{\n");
      out.write("					if (forma.tipoOrden.value == 'ASC') \n");
      out.write("						forma.tipoOrden.value = 'DESC';					\n");
      out.write("					else \n");
      out.write("						forma.tipoOrden.value = 'ASC';					\n");
      out.write("				} \n");
      out.write("				else \n");
      out.write("					forma.tipoOrden.value = 'ASC';				\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("	\n");
      out.write("		forma.submit();\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	// Modificado por: Kerwin Arias (27/08/2012)\n");
      out.write("	function cambioImagenOrden(forma) \n");
      out.write("	{\n");
      out.write("		if ((forma.atributoOrden.value != null) && (forma.atributoOrden.value != '')) \n");
      out.write("		{\n");
      out.write("			url = \"");
      if (_jspx_meth_html_005frewrite_005f0(_jspx_page_context))
        return;
      out.write("\";\n");
      out.write("			// Hace las validaciones correspondientes y dibuja las imagen\n");
      out.write("			if (forma.tipoOrden.value == \"ASC\") \n");
      out.write("				document.images[forma.atributoOrden.value].src = url + \"componentes/visorLista/arriba.gif\";\n");
      out.write("			else if (forma.tipoOrden.value == \"DESC\") \n");
      out.write("				document.images[forma.atributoOrden.value].src = url + \"componentes/visorLista/abajo.gif\";							\n");
      out.write("		}\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	function verificarObjetoSeleccionado(my_form, form_field, errorMsg, my_action, confirmMsg, multiSelect, errorSimpleSelect) \n");
      out.write("	{\n");
      out.write("		var length = my_form.elements.length;\n");
      out.write("		var index = 0;\n");
      out.write("		var checked = 0;\n");
      out.write("		var totalSelected = 0;\n");
      out.write("		for( index=0; index < length; index++ ) \n");
      out.write("		{\n");
      out.write("			if( my_form.elements[index].name == form_field && my_form.elements[index].checked  ) \n");
      out.write("			{\n");
      out.write("				checked = 1;\n");
      out.write("				totalSelected++;\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("		if ( !checked ) \n");
      out.write("		  	alert(errorMsg);\n");
      out.write("		else \n");
      out.write("		{\n");
      out.write("			if ((!multiSelect) && (totalSelected>1)) \n");
      out.write("			{\n");
      out.write("				alert(errorSimpleSelect);\n");
      out.write("				return;\n");
      out.write("			}\n");
      out.write("			res = false;\n");
      out.write("			if (confirmMsg.length > 0) \n");
      out.write("				res = confirm(confirmMsg);\n");
      out.write("			else \n");
      out.write("				res = true;\n");
      out.write("			if (res) \n");
      out.write("			{\n");
      out.write("				my_form.action = my_action;\n");
      out.write("				my_form.submit();\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	// Modificado por: Kerwin Arias (27/04/2012)\n");
      out.write("	function eventoMouseFueraFila(forma, fila) \n");
      out.write("	{\n");
      out.write("		if (forma.seleccionados.value == fila.id) \n");
      out.write("			fila.className='cuerpoListViewFilaSeleccionada';\n");
      out.write("		else \n");
      out.write("			fila.className='mouseFueraCuerpoListView';\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	// Modificado por: Kerwin Arias (27/04/2012)\n");
      out.write("	function eventoMouseEncimaFila(forma, fila) \n");
      out.write("	{\n");
      out.write("		if (forma.seleccionados.value == fila.id) \n");
      out.write("			fila.className='cuerpoListViewFilaSeleccionada';\n");
      out.write("		else \n");
      out.write("			fila.className='mouseEncimaCuerpoListView';\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	// Modificado por: Kerwin Arias (28/07/2012)\n");
      out.write("	function eventoClickFila(forma, idTabla, fila) \n");
      out.write("	{\n");
      out.write("		var seleccionadoAnterior = forma.seleccionados.value;\n");
      out.write("		if (forma.seleccionados.value != fila.id) \n");
      out.write("		{\n");
      out.write("			forma.seleccionados.value = fila.id;\n");
      out.write("			var objeto = document.getElementById('valor' + fila.id);\n");
      out.write("			if (objeto != null) \n");
      out.write("			{\n");
      out.write("				var valor = objeto.innerHTML;\n");
      out.write("				if (forma.valoresSeleccionados != null) \n");
      out.write("					forma.valoresSeleccionados.value = valor;\n");
      out.write("			}\n");
      out.write("			eventoMouseFueraFila(forma, fila);\n");
      out.write("			setImagenSeleccionadoFila(forma, fila);		\n");
      out.write("		} \n");
      out.write("		else \n");
      out.write("		{\n");
      out.write("			if (forma.valoresSeleccionados != null) \n");
      out.write("				forma.seleccionados.value = '';\n");
      out.write("		}\n");
      out.write("		if ((seleccionadoAnterior != null) && (seleccionadoAnterior != '')) \n");
      out.write("		{\n");
      out.write("			objetoFilaAnterior = document.getElementById(seleccionadoAnterior);\n");
      out.write("			if (objetoFilaAnterior != null) \n");
      out.write("			{\n");
      out.write("				eventoMouseFueraFila(forma, objetoFilaAnterior);\n");
      out.write("				setImagenSeleccionadoFila(forma, objetoFilaAnterior);		\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	// Modificado por: Kerwin Arias (28/07/2012)\n");
      out.write("	function actualizarSeleccionados(forma, idTabla) \n");
      out.write("	{\n");
      out.write("		if ((forma.seleccionados.value != null) && (forma.seleccionados.value != '')) \n");
      out.write("		{\n");
      out.write("			var fila = document.getElementById(forma.seleccionados.value);\n");
      out.write("			if (fila != null) \n");
      out.write("			{\n");
      out.write("				eventoMouseFueraFila(forma, fila);\n");
      out.write("				setImagenSeleccionadoFila(forma, fila);\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("		else\n");
      out.write("		{\n");
      out.write("			var tabla = document.getElementById(idTabla);\n");
      out.write("			var i = 0;\n");
      out.write("			for (i = 1; i < tabla.rows.length; i++) \n");
      out.write("			{\n");
      out.write("				var fila = tabla.rows[i];\n");
      out.write("				eventoMouseEncimaFila(forma, fila);\n");
      out.write("				eventoMouseFueraFila(forma, fila);\n");
      out.write("				setImagenSeleccionadoFila(forma, fila);\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	// Modificado por: Kerwin Arias (28/07/2012)\n");
      out.write("	function setImagenSeleccionadoFila(forma, fila) \n");
      out.write("	{\n");
      out.write("		// Hace las validaciones correspondientes y dibuja las imagen\n");
      out.write("		url = \"");
      if (_jspx_meth_html_005frewrite_005f1(_jspx_page_context))
        return;
      out.write("\";\n");
      out.write("		var celdas = fila.cells;\n");
      out.write("		var celdaSelector = celdas[0];\n");
      out.write("		if (celdaSelector.id != null) \n");
      out.write("		{\n");
      out.write("			if (celdaSelector.id.indexOf('selector') == 0) \n");
      out.write("			{\n");
      out.write("				if (forma.seleccionados.value == fila.id) \n");
      out.write("					celdaSelector.innerHTML = '<img src=\"' + url + 'componentes/visorLista/seleccionado.gif\" border=\"0\" width=\"10\" height=\"10\">';\n");
      out.write("				else \n");
      out.write("					celdaSelector.innerHTML = '&nbsp;';\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	// Funcion que selecciona/deselecciona todos los elementos de un\n");
      out.write("	// visor de lista\n");
      out.write("	// Creado por: Kerwin Arias (06/06/2012)\n");
      out.write("	function selectUnselectAllObject(forma, campoControl, nombreCampo) \n");
      out.write("	{\n");
      out.write("		var flag;\n");
      out.write("		if (campoControl.checked) \n");
      out.write("			flag = true;\n");
      out.write("		else \n");
      out.write("			flag = false;\n");
      out.write("		len=forma.elements.length;\n");
      out.write("		var index=0;\n");
      out.write("		for( index=0; index < len; index++ ) \n");
      out.write("		{\n");
      out.write("			if(forma.elements[index].name == nombreCampo) \n");
      out.write("				forma.elements[index].checked=flag;\n");
      out.write("		}\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	// Creado por: Kerwin Arias (10/07/2012)\n");
      out.write("	function consultarConfigurable(forma, action, campoPagina, campoAtributoOrden, campoTipoOrden, inOrden, inPagina) \n");
      out.write("	{\n");
      out.write("		if (action != null) \n");
      out.write("			forma.action = action;\n");
      out.write("	\n");
      out.write("		if (inPagina != null) \n");
      out.write("		{\n");
      out.write("			campoPagina.value = inPagina;\n");
      out.write("			forma.submit();\n");
      out.write("		}\n");
      out.write("	\n");
      out.write("		if (inOrden != null) \n");
      out.write("		{\n");
      out.write("			var cambioOrden = (campoAtributoOrden.value != inOrden);\n");
      out.write("			campoAtributoOrden.value=inOrden;\n");
      out.write("			if (cambioOrden) \n");
      out.write("				campoTipoOrden.value = 'ASC';			\n");
      out.write("			else \n");
      out.write("			{\n");
      out.write("				if (campoTipoOrden.value != null) \n");
      out.write("				{\n");
      out.write("					if (campoTipoOrden.value == 'ASC') \n");
      out.write("						campoTipoOrden.value = 'DESC';					\n");
      out.write("					else \n");
      out.write("						campoTipoOrden.value = 'ASC';					\n");
      out.write("				} \n");
      out.write("				else \n");
      out.write("					campoTipoOrden.value = 'ASC';				\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("	\n");
      out.write("		forma.submit();\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	// Creado por: Kerwin Arias (18/06/2012)\n");
      out.write("	function consultarV2(forma, campoPagina, campoAtributoOrden, campoTipoOrden, inOrden, inPagina) \n");
      out.write("	{\n");
      out.write("		if (typeof(forma.seleccionados) != \"undefined\")\n");
      out.write("			forma.seleccionados.value = \"\";\n");
      out.write("\n");
      out.write("		if (inPagina != null) \n");
      out.write("		{\n");
      out.write("			campoPagina.value = inPagina;\n");
      out.write("			forma.submit();\n");
      out.write("		}\n");
      out.write("	\n");
      out.write("		if (inOrden != null) \n");
      out.write("		{\n");
      out.write("			var cambioOrden = (campoAtributoOrden.value != inOrden);\n");
      out.write("			campoAtributoOrden.value=inOrden;\n");
      out.write("			if (cambioOrden) \n");
      out.write("				campoTipoOrden.value = 'ASC';			\n");
      out.write("			else \n");
      out.write("			{\n");
      out.write("				if (campoTipoOrden.value != null) \n");
      out.write("				{\n");
      out.write("					if (campoTipoOrden.value == 'ASC') \n");
      out.write("						campoTipoOrden.value = 'DESC';					\n");
      out.write("					else \n");
      out.write("						campoTipoOrden.value = 'ASC';					\n");
      out.write("				} \n");
      out.write("				else \n");
      out.write("					campoTipoOrden.value = 'ASC';				\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("	\n");
      out.write("		forma.submit();\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	// Creado por: Kerwin Arias (18/06/2012)\n");
      out.write("	function cambioImagenOrdenV2(campoAtributoOrden, campoTipoOrden) \n");
      out.write("	{\n");
      out.write("		url = \"");
      if (_jspx_meth_html_005frewrite_005f2(_jspx_page_context))
        return;
      out.write("\";\n");
      out.write("		// Hace las validaciones correspondientes y dibuja las imagen\n");
      out.write("		if (campoTipoOrden.value == \"ASC\") \n");
      out.write("			document.images[campoAtributoOrden.value].src = url + \"componentes/visorLista/arriba.gif\";\n");
      out.write("		else if (campoTipoOrden.value == \"DESC\") \n");
      out.write("			document.images[campoAtributoOrden.value].src = url + \"componentes/visorLista/abajo.gif\";							\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	// Creado por: Kerwin Arias (28/07/2012)\n");
      out.write("	function eventoClickFilaV2(campoIdSeleccionado, campoValorSeleccionado, idTabla, fila) \n");
      out.write("	{\n");
      out.write("		var seleccionadoAnterior = campoIdSeleccionado.value;\n");
      out.write("		if (campoIdSeleccionado.value != fila.id) \n");
      out.write("		{\n");
      out.write("			campoIdSeleccionado.value = fila.id;\n");
      out.write("			var objeto = document.getElementById('valor' + fila.id);\n");
      out.write("			if (objeto != null) \n");
      out.write("			{\n");
      out.write("				var valor = objeto.innerHTML;\n");
      out.write("				if (campoValorSeleccionado != null) \n");
      out.write("					campoValorSeleccionado.value = valor;\n");
      out.write("			}\n");
      out.write("			eventoMouseFueraFilaV2(campoIdSeleccionado, fila);\n");
      out.write("			setImagenSeleccionadoFilaV2(campoIdSeleccionado, fila);		\n");
      out.write("		} \n");
      out.write("		else \n");
      out.write("		{\n");
      out.write("			if (campoValorSeleccionado != null) \n");
      out.write("				campoIdSeleccionado.value = '';\n");
      out.write("		}\n");
      out.write("		if ((seleccionadoAnterior != null) && (seleccionadoAnterior != '')) \n");
      out.write("		{\n");
      out.write("			objetoFilaAnterior = document.getElementById(seleccionadoAnterior);\n");
      out.write("			if (objetoFilaAnterior != null) \n");
      out.write("			{\n");
      out.write("				eventoMouseFueraFilaV2(campoIdSeleccionado, objetoFilaAnterior);\n");
      out.write("				setImagenSeleccionadoFilaV2(campoIdSeleccionado, objetoFilaAnterior);		\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	// Modificado por: Kerwin Arias (28/07/2012)\n");
      out.write("	function actualizarSeleccionadosV2(campoIdSeleccionado, idTabla) \n");
      out.write("	{\n");
      out.write("		if ((campoIdSeleccionado.value != null) && (campoIdSeleccionado.value != '')) \n");
      out.write("		{\n");
      out.write("			var fila = document.getElementById(campoIdSeleccionado.value);\n");
      out.write("			if (fila != null) \n");
      out.write("			{\n");
      out.write("				eventoMouseFueraFilaV2(campoIdSeleccionado, fila);\n");
      out.write("				setImagenSeleccionadoFilaV2(campoIdSeleccionado, fila);\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	// Creado por: Kerwin Arias (18/06/2012)\n");
      out.write("	function eventoMouseFueraFilaV2(campoIdSeleccionado, fila) \n");
      out.write("	{\n");
      out.write("		if (campoIdSeleccionado.value != fila.id) \n");
      out.write("			fila.className='mouseFueraCuerpoListView';\n");
      out.write("		else \n");
      out.write("			fila.className='cuerpoListViewFilaSeleccionada';\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	// Creado por: Kerwin Arias (18/06/2012)\n");
      out.write("	function eventoMouseEncimaFilaV2(campoIdSeleccionado, fila) \n");
      out.write("	{\n");
      out.write("		if (campoIdSeleccionado.value != fila.id) \n");
      out.write("			fila.className='mouseEncimaCuerpoListView';\n");
      out.write("		else \n");
      out.write("			fila.className='cuerpoListViewFilaSeleccionada';\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	// Creado por: Kerwin Arias (18/06/2012)\n");
      out.write("	function setImagenSeleccionadoFilaV2(campoIdSeleccionado, fila) \n");
      out.write("	{\n");
      out.write("		// Hace las validaciones correspondientes y dibuja las imagen\n");
      out.write("		url = \"");
      if (_jspx_meth_html_005frewrite_005f3(_jspx_page_context))
        return;
      out.write("\";\n");
      out.write("		var celdas = fila.cells;\n");
      out.write("		var celdaSelector = celdas[0];\n");
      out.write("		if (celdaSelector.id != null) \n");
      out.write("		{\n");
      out.write("			if (celdaSelector.id.indexOf('selector') == 0) \n");
      out.write("			{\n");
      out.write("				if (campoIdSeleccionado.value == fila.id) \n");
      out.write("					celdaSelector.innerHTML = '<img src=\"' + url + 'componentes/visorLista/seleccionado.gif\" border=\"0\" width=\"10\" height=\"10\">';\n");
      out.write("				else \n");
      out.write("					celdaSelector.innerHTML = '&nbsp;';\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	function inicializarVisorListaSeleccionSimple(campoIdSeleccionado, idTabla) \n");
      out.write("	{\n");
      out.write("		actualizarSeleccionadosV2(campoIdSeleccionado, idTabla);\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	// ******************************************************\n");
      out.write("	// *** Funciones de Visor Lista de Seleccion Multiple ***\n");
      out.write("	// ******************************************************\n");
      out.write("	\n");
      out.write("	// Creado por: Kerwin Arias (27/08/2012)\n");
      out.write("	function getValorFilaSeleccionMultiple(filaId) \n");
      out.write("	{\n");
      out.write("	    var objeto = document.getElementById('valor' + filaId);\n");
      out.write("		if (objeto != null) {\n");
      out.write("		  var valor = objeto.innerHTML;\n");
      out.write("		  if (valor != null) \n");
      out.write("			 return valor;\n");
      out.write("		  else \n");
      out.write("		     return ''; \n");
      out.write("		} \n");
      out.write("		else \n");
      out.write("			return ''; \n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	// Creado por: Kerwin Arias (27/08/2012)\n");
      out.write("	function eventoClickFilaSeleccionMultiple(campoIdsSeleccionados, campoValoresSeleccionados, idTabla, fila) \n");
      out.write("	{\n");
      out.write("		if ((campoIdsSeleccionados.value == null) || (campoIdsSeleccionados.value == '') || (campoIdsSeleccionados.value == 'null')) \n");
      out.write("			campoIdsSeleccionados.value = \",\";\n");
      out.write("		else \n");
      out.write("			campoIdsSeleccionados.value = \",\" + campoIdsSeleccionados.value + \",\";\n");
      out.write("	\n");
      out.write("		if (campoValoresSeleccionados != null) \n");
      out.write("		{\n");
      out.write("			if ((campoValoresSeleccionados.value == null) || (campoValoresSeleccionados.value == '') || (campoValoresSeleccionados.value == 'null')) \n");
      out.write("				campoValoresSeleccionados.value = \",\";\n");
      out.write("			else \n");
      out.write("				campoValoresSeleccionados.value = \",\" + campoValoresSeleccionados.value + \",\";\n");
      out.write("		}\n");
      out.write("			\n");
      out.write("		var index = campoIdsSeleccionados.value.indexOf(',' + fila.id + ',');\n");
      out.write("		if (index < 0) \n");
      out.write("		{\n");
      out.write("			campoIdsSeleccionados.value = campoIdsSeleccionados.value + fila.id + ',';\n");
      out.write("			if (campoValoresSeleccionados != null) \n");
      out.write("				campoValoresSeleccionados.value = campoValoresSeleccionados.value + getValorFilaSeleccionMultiple(fila.id) + \",\";\n");
      out.write("		} \n");
      out.write("		else \n");
      out.write("		{\n");
      out.write("			campoIdsSeleccionados.value = campoIdsSeleccionados.value.replace(',' + fila.id + ',',',');		\n");
      out.write("			if (campoValoresSeleccionados != null) \n");
      out.write("				campoValoresSeleccionados.value = campoValoresSeleccionados.value.replace(',' + getValorFilaSeleccionMultiple(fila.id) + ',',',');		\n");
      out.write("		} \n");
      out.write("	\n");
      out.write("	    campoIdsSeleccionados.value = campoIdsSeleccionados.value.substring(1, campoIdsSeleccionados.value.length);\n");
      out.write("		if (campoValoresSeleccionados != null) \n");
      out.write("			campoValoresSeleccionados.value = campoValoresSeleccionados.value.substring(1, campoValoresSeleccionados.value.length);\n");
      out.write("	\n");
      out.write("		if (campoIdsSeleccionados.value != '') \n");
      out.write("		{\n");
      out.write("			campoIdsSeleccionados.value = campoIdsSeleccionados.value.substring(0, campoIdsSeleccionados.value.length-1);\n");
      out.write("			if (campoValoresSeleccionados != null) \n");
      out.write("				campoValoresSeleccionados.value = campoValoresSeleccionados.value.substring(0, campoValoresSeleccionados.value.length-1);\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		actualizarSeleccionadosSeleccionMultiple(campoIdsSeleccionados, idTabla);\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	// Creado por: Kerwin Arias (19/01/2012)\n");
      out.write("	function eventoMouseFueraFilaSeleccionMultiple(campoIdsSeleccionados, fila) \n");
      out.write("	{\n");
      out.write("		if (fila.id == campoIdsSeleccionados.value) \n");
      out.write("			fila.className='cuerpoListViewFilaSeleccionada';\n");
      out.write("		else if (campoIdsSeleccionados.value.indexOf(fila.id + ',') == 0) \n");
      out.write("			fila.className='cuerpoListViewFilaSeleccionada';\n");
      out.write("		else if (campoIdsSeleccionados.value.indexOf(',' + fila.id + ',') > -1) \n");
      out.write("			fila.className='cuerpoListViewFilaSeleccionada';\n");
      out.write("		else \n");
      out.write("		{\n");
      out.write("			var index = campoIdsSeleccionados.value.length - fila.id.length - ','.length;\n");
      out.write("			if ((campoIdsSeleccionados.value.indexOf(',' + fila.id) == index) && (index > -1)) \n");
      out.write("				fila.className='cuerpoListViewFilaSeleccionada';\n");
      out.write("			else \n");
      out.write("				fila.className='mouseFueraCuerpoListView';\n");
      out.write("		}\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	// Creado por: Kerwin Arias (19/01/2012)\n");
      out.write("	function eventoMouseEncimaFilaSeleccionMultiple(campoIdsSeleccionados, fila) \n");
      out.write("	{\n");
      out.write("		if (fila.id == campoIdsSeleccionados.value) \n");
      out.write("			fila.className='cuerpoListViewFilaSeleccionada';\n");
      out.write("		else if (campoIdsSeleccionados.value.indexOf(fila.id + ',') == 0) \n");
      out.write("			fila.className='cuerpoListViewFilaSeleccionada';\n");
      out.write("		else if (campoIdsSeleccionados.value.indexOf(',' + fila.id + ',') > -1) \n");
      out.write("			fila.className='cuerpoListViewFilaSeleccionada';\n");
      out.write("		else \n");
      out.write("		{\n");
      out.write("			var index = campoIdsSeleccionados.value.length - fila.id.length - ','.length;\n");
      out.write("	\n");
      out.write("			if ((campoIdsSeleccionados.value.indexOf(',' + fila.id) == index) && (index > -1)) \n");
      out.write("				fila.className='cuerpoListViewFilaSeleccionada';\n");
      out.write("			else \n");
      out.write("				fila.className='mouseEncimaCuerpoListView';\n");
      out.write("		}\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	function setImagenSeleccionadoFilaSeleccionMultiple(campoIdsSeleccionados, fila) \n");
      out.write("	{\n");
      out.write("		// Hace las validaciones correspondientes y dibuja las imagen\n");
      out.write("		url = \"");
      if (_jspx_meth_html_005frewrite_005f4(_jspx_page_context))
        return;
      out.write("\";\n");
      out.write("		if (document.images['img' + fila.id] != null) \n");
      out.write("		{\n");
      out.write("			if (fila.id == campoIdsSeleccionados.value) \n");
      out.write("			{\n");
      out.write("				document.images['img' + fila.id].src = url + \"componentes/visorLista/seleccionado.gif\";\n");
      out.write("				document.images['img' + fila.id].title = '");
      if (_jspx_meth_vgcutil_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("';\n");
      out.write("			} \n");
      out.write("			else if (campoIdsSeleccionados.value.indexOf(fila.id + ',') == 0) \n");
      out.write("			{			\n");
      out.write("				document.images['img' + fila.id].src = url + \"componentes/visorLista/seleccionado.gif\";\n");
      out.write("				document.images['img' + fila.id].title = '");
      if (_jspx_meth_vgcutil_005fmessage_005f1(_jspx_page_context))
        return;
      out.write("';			\n");
      out.write("			} \n");
      out.write("			else if (campoIdsSeleccionados.value.indexOf(',' + fila.id + ',') > -1) \n");
      out.write("			{\n");
      out.write("				document.images['img' + fila.id].src = url + \"componentes/visorLista/seleccionado.gif\";\n");
      out.write("				document.images['img' + fila.id].title = '");
      if (_jspx_meth_vgcutil_005fmessage_005f2(_jspx_page_context))
        return;
      out.write("';\n");
      out.write("			} \n");
      out.write("			else \n");
      out.write("			{\n");
      out.write("				var index = campoIdsSeleccionados.value.length - fila.id.length - ','.length;\n");
      out.write("		\n");
      out.write("				if ((campoIdsSeleccionados.value.indexOf(',' + fila.id) == index) && (index > -1)) \n");
      out.write("				{\n");
      out.write("					document.images['img' + fila.id].src = url + \"componentes/visorLista/seleccionado.gif\";\n");
      out.write("					document.images['img' + fila.id].title = '");
      if (_jspx_meth_vgcutil_005fmessage_005f3(_jspx_page_context))
        return;
      out.write("';\n");
      out.write("	\n");
      out.write("				} \n");
      out.write("				else \n");
      out.write("					document.images['img' + fila.id].src = url + \"componentes/visorLista/transparente.gif\";\n");
      out.write("			}	\n");
      out.write("		}\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	// Creado por: Kerwin Arias (10/07/2012)\n");
      out.write("	function actualizarSeleccionadosSeleccionMultiple(campoIdsSeleccionados, idTabla) \n");
      out.write("	{\n");
      out.write("		var tabla = document.getElementById(idTabla);\n");
      out.write("		var total = tabla.rows.length;\n");
      out.write("		for (i = 1; i < total; i++) \n");
      out.write("		{\n");
      out.write("			var fila = tabla.rows[i];\n");
      out.write("			eventoMouseEncimaFilaSeleccionMultiple(campoIdsSeleccionados, fila);\n");
      out.write("			eventoMouseFueraFilaSeleccionMultiple(campoIdsSeleccionados, fila);\n");
      out.write("			setImagenSeleccionadoFilaSeleccionMultiple(campoIdsSeleccionados, fila);\n");
      out.write("		}\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	// Creado por: Kerwin Arias (16/01/2012)\n");
      out.write("	function inicializarVisorListaSeleccionMultiple(campoIdsSeleccionados, idTabla) \n");
      out.write("	{\n");
      out.write("		actualizarSeleccionadosSeleccionMultiple(campoIdsSeleccionados, idTabla);\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	function verificarElementoUnicoSeleccionMultiple(campoIdsSeleccionados) \n");
      out.write("	{\n");
      out.write("		if ((campoIdsSeleccionados.value == null) || (campoIdsSeleccionados.value == '')) \n");
      out.write("		{\n");
      out.write("			alert('Debe seleccionar un elemento para poder ejecutar la operación seleccionada');\n");
      out.write("			return false;\n");
      out.write("		} \n");
      out.write("		else if (campoIdsSeleccionados.value.indexOf(',') > -1) \n");
      out.write("		{\n");
      out.write("			alert('Debe seleccionar un solo elemento para poder ejecutar la operación seleccionada');\n");
      out.write("			return false;\n");
      out.write("		} \n");
      out.write("		else \n");
      out.write("			return true;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	function verificarSeleccionMultiple(campoIdsSeleccionados) \n");
      out.write("	{\n");
      out.write("		if ((campoIdsSeleccionados.value == null) || (campoIdsSeleccionados.value == '')) \n");
      out.write("		{\n");
      out.write("			alert('Debe seleccionar un elemento para poder ejecutar la operación seleccionada');\n");
      out.write("			return false;\n");
      out.write("		} \n");
      out.write("		else \n");
      out.write("			return true;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	function getObjetos(campoIdsSeleccionados)\n");
      out.write("	{\n");
      out.write("		var arrObjetosId = new Array(0);\n");
      out.write("		\n");
      out.write("		if ((campoIdsSeleccionados.value != null) || (campoIdsSeleccionados.value =! '')) \n");
      out.write("			arrObjetosId = campoIdsSeleccionados.value.split(\",\");\n");
      out.write("	\n");
      out.write("		return arrObjetosId;\n");
      out.write("	}\n");
      out.write("\n");
      out.write("//</script>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_html_005frewrite_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:rewrite
    org.apache.struts.taglib.html.RewriteTag _jspx_th_html_005frewrite_005f0 = (org.apache.struts.taglib.html.RewriteTag) _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.get(org.apache.struts.taglib.html.RewriteTag.class);
    boolean _jspx_th_html_005frewrite_005f0_reused = false;
    try {
      _jspx_th_html_005frewrite_005f0.setPageContext(_jspx_page_context);
      _jspx_th_html_005frewrite_005f0.setParent(null);
      // /componentes/visorLista/visorListaJsTag.jsp(50,10) name = page type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005frewrite_005f0.setPage("/");
      int _jspx_eval_html_005frewrite_005f0 = _jspx_th_html_005frewrite_005f0.doStartTag();
      if (_jspx_th_html_005frewrite_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.reuse(_jspx_th_html_005frewrite_005f0);
      _jspx_th_html_005frewrite_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005frewrite_005f0, _jsp_getInstanceManager(), _jspx_th_html_005frewrite_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005frewrite_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:rewrite
    org.apache.struts.taglib.html.RewriteTag _jspx_th_html_005frewrite_005f1 = (org.apache.struts.taglib.html.RewriteTag) _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.get(org.apache.struts.taglib.html.RewriteTag.class);
    boolean _jspx_th_html_005frewrite_005f1_reused = false;
    try {
      _jspx_th_html_005frewrite_005f1.setPageContext(_jspx_page_context);
      _jspx_th_html_005frewrite_005f1.setParent(null);
      // /componentes/visorLista/visorListaJsTag.jsp(176,9) name = page type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005frewrite_005f1.setPage("/");
      int _jspx_eval_html_005frewrite_005f1 = _jspx_th_html_005frewrite_005f1.doStartTag();
      if (_jspx_th_html_005frewrite_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.reuse(_jspx_th_html_005frewrite_005f1);
      _jspx_th_html_005frewrite_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005frewrite_005f1, _jsp_getInstanceManager(), _jspx_th_html_005frewrite_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005frewrite_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:rewrite
    org.apache.struts.taglib.html.RewriteTag _jspx_th_html_005frewrite_005f2 = (org.apache.struts.taglib.html.RewriteTag) _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.get(org.apache.struts.taglib.html.RewriteTag.class);
    boolean _jspx_th_html_005frewrite_005f2_reused = false;
    try {
      _jspx_th_html_005frewrite_005f2.setPageContext(_jspx_page_context);
      _jspx_th_html_005frewrite_005f2.setParent(null);
      // /componentes/visorLista/visorListaJsTag.jsp(283,9) name = page type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005frewrite_005f2.setPage("/");
      int _jspx_eval_html_005frewrite_005f2 = _jspx_th_html_005frewrite_005f2.doStartTag();
      if (_jspx_th_html_005frewrite_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.reuse(_jspx_th_html_005frewrite_005f2);
      _jspx_th_html_005frewrite_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005frewrite_005f2, _jsp_getInstanceManager(), _jspx_th_html_005frewrite_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005frewrite_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:rewrite
    org.apache.struts.taglib.html.RewriteTag _jspx_th_html_005frewrite_005f3 = (org.apache.struts.taglib.html.RewriteTag) _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.get(org.apache.struts.taglib.html.RewriteTag.class);
    boolean _jspx_th_html_005frewrite_005f3_reused = false;
    try {
      _jspx_th_html_005frewrite_005f3.setPageContext(_jspx_page_context);
      _jspx_th_html_005frewrite_005f3.setParent(null);
      // /componentes/visorLista/visorListaJsTag.jsp(360,9) name = page type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005frewrite_005f3.setPage("/");
      int _jspx_eval_html_005frewrite_005f3 = _jspx_th_html_005frewrite_005f3.doStartTag();
      if (_jspx_th_html_005frewrite_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.reuse(_jspx_th_html_005frewrite_005f3);
      _jspx_th_html_005frewrite_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005frewrite_005f3, _jsp_getInstanceManager(), _jspx_th_html_005frewrite_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005frewrite_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:rewrite
    org.apache.struts.taglib.html.RewriteTag _jspx_th_html_005frewrite_005f4 = (org.apache.struts.taglib.html.RewriteTag) _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.get(org.apache.struts.taglib.html.RewriteTag.class);
    boolean _jspx_th_html_005frewrite_005f4_reused = false;
    try {
      _jspx_th_html_005frewrite_005f4.setPageContext(_jspx_page_context);
      _jspx_th_html_005frewrite_005f4.setParent(null);
      // /componentes/visorLista/visorListaJsTag.jsp(486,9) name = page type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005frewrite_005f4.setPage("/");
      int _jspx_eval_html_005frewrite_005f4 = _jspx_th_html_005frewrite_005f4.doStartTag();
      if (_jspx_th_html_005frewrite_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.reuse(_jspx_th_html_005frewrite_005f4);
      _jspx_th_html_005frewrite_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005frewrite_005f4, _jsp_getInstanceManager(), _jspx_th_html_005frewrite_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_vgcutil_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  vgcutil:message
    com.visiongc.commons.struts.tag.MessageTag _jspx_th_vgcutil_005fmessage_005f0 = (com.visiongc.commons.struts.tag.MessageTag) _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.get(com.visiongc.commons.struts.tag.MessageTag.class);
    boolean _jspx_th_vgcutil_005fmessage_005f0_reused = false;
    try {
      _jspx_th_vgcutil_005fmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_vgcutil_005fmessage_005f0.setParent(null);
      // /componentes/visorLista/visorListaJsTag.jsp(492,46) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_vgcutil_005fmessage_005f0.setKey("commons.seleccionado");
      int _jspx_eval_vgcutil_005fmessage_005f0 = _jspx_th_vgcutil_005fmessage_005f0.doStartTag();
      if (_jspx_th_vgcutil_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_vgcutil_005fmessage_005f0);
      _jspx_th_vgcutil_005fmessage_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_vgcutil_005fmessage_005f0, _jsp_getInstanceManager(), _jspx_th_vgcutil_005fmessage_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_vgcutil_005fmessage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  vgcutil:message
    com.visiongc.commons.struts.tag.MessageTag _jspx_th_vgcutil_005fmessage_005f1 = (com.visiongc.commons.struts.tag.MessageTag) _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.get(com.visiongc.commons.struts.tag.MessageTag.class);
    boolean _jspx_th_vgcutil_005fmessage_005f1_reused = false;
    try {
      _jspx_th_vgcutil_005fmessage_005f1.setPageContext(_jspx_page_context);
      _jspx_th_vgcutil_005fmessage_005f1.setParent(null);
      // /componentes/visorLista/visorListaJsTag.jsp(497,46) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_vgcutil_005fmessage_005f1.setKey("commons.seleccionado");
      int _jspx_eval_vgcutil_005fmessage_005f1 = _jspx_th_vgcutil_005fmessage_005f1.doStartTag();
      if (_jspx_th_vgcutil_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_vgcutil_005fmessage_005f1);
      _jspx_th_vgcutil_005fmessage_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_vgcutil_005fmessage_005f1, _jsp_getInstanceManager(), _jspx_th_vgcutil_005fmessage_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_vgcutil_005fmessage_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  vgcutil:message
    com.visiongc.commons.struts.tag.MessageTag _jspx_th_vgcutil_005fmessage_005f2 = (com.visiongc.commons.struts.tag.MessageTag) _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.get(com.visiongc.commons.struts.tag.MessageTag.class);
    boolean _jspx_th_vgcutil_005fmessage_005f2_reused = false;
    try {
      _jspx_th_vgcutil_005fmessage_005f2.setPageContext(_jspx_page_context);
      _jspx_th_vgcutil_005fmessage_005f2.setParent(null);
      // /componentes/visorLista/visorListaJsTag.jsp(502,46) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_vgcutil_005fmessage_005f2.setKey("commons.seleccionado");
      int _jspx_eval_vgcutil_005fmessage_005f2 = _jspx_th_vgcutil_005fmessage_005f2.doStartTag();
      if (_jspx_th_vgcutil_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_vgcutil_005fmessage_005f2);
      _jspx_th_vgcutil_005fmessage_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_vgcutil_005fmessage_005f2, _jsp_getInstanceManager(), _jspx_th_vgcutil_005fmessage_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_vgcutil_005fmessage_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  vgcutil:message
    com.visiongc.commons.struts.tag.MessageTag _jspx_th_vgcutil_005fmessage_005f3 = (com.visiongc.commons.struts.tag.MessageTag) _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.get(com.visiongc.commons.struts.tag.MessageTag.class);
    boolean _jspx_th_vgcutil_005fmessage_005f3_reused = false;
    try {
      _jspx_th_vgcutil_005fmessage_005f3.setPageContext(_jspx_page_context);
      _jspx_th_vgcutil_005fmessage_005f3.setParent(null);
      // /componentes/visorLista/visorListaJsTag.jsp(511,47) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_vgcutil_005fmessage_005f3.setKey("commons.seleccionado");
      int _jspx_eval_vgcutil_005fmessage_005f3 = _jspx_th_vgcutil_005fmessage_005f3.doStartTag();
      if (_jspx_th_vgcutil_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fvgcutil_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_vgcutil_005fmessage_005f3);
      _jspx_th_vgcutil_005fmessage_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_vgcutil_005fmessage_005f3, _jsp_getInstanceManager(), _jspx_th_vgcutil_005fmessage_005f3_reused);
    }
    return false;
  }
}
