/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2022-08-01 22:45:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.componentes.comunes;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class includeJsComunes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/tld/struts-html.tld", Long.valueOf(1646829840000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_html_005frewrite_005f0(_jspx_page_context))
        return;
      out.write("\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_html_005frewrite_005f1(_jspx_page_context))
        return;
      out.write("\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_html_005frewrite_005f2(_jspx_page_context))
        return;
      out.write("\"></script>\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("	#dialog-overlay \n");
      out.write("	{\n");
      out.write("		position:absolute;\n");
      out.write("		top:0px;\n");
      out.write("		left:0px;\n");
      out.write("		width:100%;\n");
      out.write("		height:100%;\n");
      out.write("		background-color: #fff;\n");
      out.write("	  	filter:alpha(opacity=60);\n");
      out.write("	  	-moz-opacity: 0.6;\n");
      out.write("	  	opacity: 0.6;\n");
      out.write("	  	cursor:wait;\n");
      out.write("		visibility: hidden;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	#dialog-bottom\n");
      out.write("	{\n");
      out.write("		visibility: visible;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	#dialog-box \n");
      out.write("	{\n");
      out.write("		/* css3 drop shadow */\n");
      out.write("		-webkit-box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.5);\n");
      out.write("		-moz-box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.5);\n");
      out.write("		\n");
      out.write("		/* css3 border radius */\n");
      out.write("		-moz-border-radius: 5px;\n");
      out.write("	    -webkit-border-radius: 5px;\n");
      out.write("		\n");
      out.write("		background-color: #fff;\n");
      out.write("     	border:1px solid #000;\n");
      out.write("		/* styling of the dialog box, i have a fixed dimension for this demo */ \n");
      out.write("		width:220px; \n");
      out.write("		\n");
      out.write("		/* make sure it has the highest z-index */\n");
      out.write("		position:absolute; \n");
      out.write("		z-index:5000; \n");
      out.write("	\n");
      out.write("		/* hide it by default */\n");
      out.write("		display:none;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	#dialog-box .dialog-content \n");
      out.write("	{\n");
      out.write("		/* style the content */\n");
      out.write("		text-align:left; \n");
      out.write("		margin:2px;\n");
      out.write("		color:#666; \n");
      out.write("		font-family:arial;\n");
      out.write("		font-size:11px; \n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	#dialog-box .dialog-content ul \n");
      out.write("	{\n");
      out.write("		margin:10px 0 10px 20px; \n");
      out.write("		padding:0; \n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	a.button \n");
      out.write("	{\n");
      out.write("		/* styles for button */\n");
      out.write("		margin:10px auto 0 auto;\n");
      out.write("		text-align:center;\n");
      out.write("		background-color: #e33100;\n");
      out.write("		display: block;\n");
      out.write("		width:50px;\n");
      out.write("		padding: 5px 10px 6px;\n");
      out.write("		color: #fff;\n");
      out.write("		text-decoration: none;\n");
      out.write("		font-weight: bold;\n");
      out.write("		line-height: 1;\n");
      out.write("		\n");
      out.write("		/* css3 implementation :) */\n");
      out.write("		-moz-border-radius: 5px;\n");
      out.write("		-webkit-border-radius: 5px;\n");
      out.write("		-moz-box-shadow: 0 1px 3px rgba(0,0,0,0.5);\n");
      out.write("		-webkit-box-shadow: 0 1px 3px rgba(0,0,0,0.5);\n");
      out.write("		text-shadow: 0 -1px 1px rgba(0,0,0,0.25);\n");
      out.write("		border-bottom: 1px solid rgba(0,0,0,0.25);\n");
      out.write("		position: relative;\n");
      out.write("		cursor: pointer;\n");
      out.write("		\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	a.button:hover \n");
      out.write("	{\n");
      out.write("		background-color: #c33100;	\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	/* extra styling */\n");
      out.write("	#dialog-box .dialog-content p \n");
      out.write("	{\n");
      out.write("		font-weight:700; margin:0;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	#overlay \n");
      out.write("	{\n");
      out.write("		visibility: hidden;\n");
      out.write("	    position: absolute;\n");
      out.write("	    left: 0px;\n");
      out.write("	    top: 0px;\n");
      out.write("	    width:100%;\n");
      out.write("	    height:100%;\n");
      out.write("	    text-align:center;\n");
      out.write("	    z-index: 1000;\n");
      out.write("	    /*background-image:url(background-trans.png);*/\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	#overlay div \n");
      out.write("	{\n");
      out.write("    	width:300px;\n");
      out.write("     	margin: 100px auto;\n");
      out.write("     	background-color: #fff;\n");
      out.write("     	border:1px solid #000;\n");
      out.write("     	padding:15px;\n");
      out.write("     	text-align:center;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	#dialog-titulo\n");
      out.write("	{\n");
      out.write("		color:#ffffff;\n");
      out.write("		padding: 5px;\n");
      out.write("		background-color: #666666;\n");
      out.write("		font-size:12px; \n");
      out.write("		font-weight: bold;\n");
      out.write("		text-align:center;\n");
      out.write("  		font-weight: lighter;		\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	#dialog-message\n");
      out.write("	{\n");
      out.write("		padding: 5px;\n");
      out.write("		font-size:12px;\n");
      out.write("		text-decoration: none;\n");
      out.write("		font-family: Verdana;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	#dialog-message a:link \n");
      out.write("	{ \n");
      out.write("		text-decoration: none;\n");
      out.write("		color :  #666666;\n");
      out.write("	} \n");
      out.write("\n");
      out.write("	#dialog-message a:active \n");
      out.write("	{ \n");
      out.write("		text-decoration: none;\n");
      out.write("		color :  #666666;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	#dialog-message a:visited \n");
      out.write("	{ \n");
      out.write("		text-decoration: none;\n");
      out.write("		color :  #666666;\n");
      out.write("	}	\n");
      out.write("\n");
      out.write("	#fondo\n");
      out.write("	{\n");
      out.write("		position:absolute;\n");
      out.write("		top:0px;\n");
      out.write("		left:0px;\n");
      out.write("		width:100%;\n");
      out.write("		height:100%;\n");
      out.write("		background-color: #fff;\n");
      out.write("	  	filter:alpha(opacity=60);\n");
      out.write("	  	-moz-opacity: 0.6;\n");
      out.write("	  	opacity: 0.6;\n");
      out.write("	  	cursor:wait;\n");
      out.write("	  	visibility: hidden;\n");
      out.write("	}\n");
      out.write("		\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	\n");
      out.write("	$(document).bind('keydown',function(e)\n");
      out.write("	{\n");
      out.write("	    if ( e.which == 27 ) \n");
      out.write("	    {\n");
      out.write("	    	closePopUp();\n");
      out.write("	    	closeDialog();\n");
      out.write("	    };\n");
      out.write("	});\n");
      out.write("\n");
      out.write("	function closeDialog()\n");
      out.write("	{\n");
      out.write("		if (_dialogOpen)\n");
      out.write("		{\n");
      out.write("			$('#dialog-overlay, #dialog-box').hide();\n");
      out.write("			$('#fondo').css({visibility: \"hidden\"});\n");
      out.write("		}\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	function closePopUp()\n");
      out.write("	{\n");
      out.write("		$('#overlay').css({visibility: \"hidden\"});\n");
      out.write("		$('#fondo').css({visibility: \"hidden\"});\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	function OnKeyPress()\n");
      out.write("	{\n");
      out.write("		closePopUp();\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	function getAbsoluteElementPosition(element) \n");
      out.write("	{\n");
      out.write("		if (typeof element == \"string\")\n");
      out.write("			element = document.getElementById(element);\n");
      out.write("		    \n");
      out.write("		if (!element) return { top:0,left:0 };\n");
      out.write("		  \n");
      out.write("		var y = 0;\n");
      out.write("		var x = 0;\n");
      out.write("		while (element.offsetParent) \n");
      out.write("		{\n");
      out.write("			x += element.offsetLeft;\n");
      out.write("		    y += element.offsetTop;\n");
      out.write("		    element = element.offsetParent;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		return {top:y,left:x};\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	/// <summary>\n");
      out.write("	/// Public method that return an object with the x,y coordinates for the object based on the document container.\n");
      out.write("	/// </summary>\n");
      out.write("	/// <param name=\"object\">The DOM object for which to find the coordinates.</param>\n");
      out.write("	/// <param name=\"relativeTo\">String indicating the location of the coordinates relative to the object; by default the lower-left corner is returned.</param>\n");
      out.write("	/// <returns>Object with x, y coordinates as properties.</returns>\n");
      out.write("	function GetObjectCoordinates(object, relativeTo)\n");
      out.write("	{\n");
      out.write("		var o = object;\n");
      out.write("		var x = 0;\n");
      out.write("		var y = 0;\n");
      out.write("		\n");
      out.write("		if (o.offsetLeft != -1 && o.offsetTop != -1)\n");
      out.write("		{\n");
      out.write("			if (relativeTo == \"center\")\n");
      out.write("			{\n");
      out.write("				x = o.offsetLeft + Math.round(object.offsetWidth / 2);\n");
      out.write("				y = o.offsetTop + Math.round(object.offsetHeight / 2);\n");
      out.write("\n");
      out.write("	        }\n");
      out.write("	        else if (relativeTo == \"top-left\")\n");
      out.write("	        {\n");
      out.write("	            x = o.offsetLeft + 4;\n");
      out.write("	            y = o.offsetTop;\n");
      out.write("	        }\n");
      out.write("	        else if (relativeTo == \"top-right\")\n");
      out.write("	        {\n");
      out.write("	            x = o.offsetLeft + object.offsetWidth;\n");
      out.write("	            y = o.offsetTop;\n");
      out.write("	        }\n");
      out.write("			else\n");
      out.write("			{\n");
      out.write("				x = o.offsetLeft + 4;\n");
      out.write("				y = o.offsetTop + o.offsetHeight;\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("\n");
      out.write("		while (o.offsetParent != null)\n");
      out.write("		{\n");
      out.write("			o = o.offsetParent;\n");
      out.write("			x += o.offsetLeft - o.scrollLeft;\n");
      out.write("			y += o.offsetTop - o.scrollTop;\n");
      out.write("		}\n");
      out.write("\n");
      out.write("		return { x: x, y: y };\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("</script>	\n");
      out.write("\n");
      out.write("<!-- Dialogo Box Solo Java Script -->\n");
      out.write("<div id=\"overlay\">\n");
      out.write("   	<div>\n");
      out.write("       	<p>Aquí va el contenido que desea mostrar al usuario.</p>\n");
      out.write("       	<a href=\"javascript:closePopUp();\" class=\"button\">Close</a>\n");
      out.write("   	</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- Dialogo Box --> \n");
      out.write("<div id=\"dialog-overlay\"></div>\n");
      out.write("<div id=\"dialog-box\">\n");
      out.write("	<div class=\"dialog-content\">\n");
      out.write("		<div id=\"dialog-titulo\"></div>\n");
      out.write("		<div id=\"dialog-message\"></div>\n");
      out.write("		<div id=\"dialog-bottom\" align=\"right\">\n");
      out.write("			<a href=\"javascript:closeDialog();\" class=\"button\">Close</a>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_html_005frewrite_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:rewrite
    org.apache.struts.taglib.html.RewriteTag _jspx_th_html_005frewrite_005f0 = (org.apache.struts.taglib.html.RewriteTag) _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.get(org.apache.struts.taglib.html.RewriteTag.class);
    boolean _jspx_th_html_005frewrite_005f0_reused = false;
    try {
      _jspx_th_html_005frewrite_005f0.setPageContext(_jspx_page_context);
      _jspx_th_html_005frewrite_005f0.setParent(null);
      // /componentes/comunes/includeJsComunes.jsp(3,36) name = page type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005frewrite_005f0.setPage("/componentes/comunes/jsComunes.jsp");
      int _jspx_eval_html_005frewrite_005f0 = _jspx_th_html_005frewrite_005f0.doStartTag();
      if (_jspx_th_html_005frewrite_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.reuse(_jspx_th_html_005frewrite_005f0);
      _jspx_th_html_005frewrite_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005frewrite_005f0, _jsp_getInstanceManager(), _jspx_th_html_005frewrite_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005frewrite_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:rewrite
    org.apache.struts.taglib.html.RewriteTag _jspx_th_html_005frewrite_005f1 = (org.apache.struts.taglib.html.RewriteTag) _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.get(org.apache.struts.taglib.html.RewriteTag.class);
    boolean _jspx_th_html_005frewrite_005f1_reused = false;
    try {
      _jspx_th_html_005frewrite_005f1.setPageContext(_jspx_page_context);
      _jspx_th_html_005frewrite_005f1.setParent(null);
      // /componentes/comunes/includeJsComunes.jsp(4,36) name = page type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005frewrite_005f1.setPage("/componentes/validaciones/validacionesJs.js");
      int _jspx_eval_html_005frewrite_005f1 = _jspx_th_html_005frewrite_005f1.doStartTag();
      if (_jspx_th_html_005frewrite_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.reuse(_jspx_th_html_005frewrite_005f1);
      _jspx_th_html_005frewrite_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005frewrite_005f1, _jsp_getInstanceManager(), _jspx_th_html_005frewrite_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_html_005frewrite_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  html:rewrite
    org.apache.struts.taglib.html.RewriteTag _jspx_th_html_005frewrite_005f2 = (org.apache.struts.taglib.html.RewriteTag) _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.get(org.apache.struts.taglib.html.RewriteTag.class);
    boolean _jspx_th_html_005frewrite_005f2_reused = false;
    try {
      _jspx_th_html_005frewrite_005f2.setPageContext(_jspx_page_context);
      _jspx_th_html_005frewrite_005f2.setParent(null);
      // /componentes/comunes/includeJsComunes.jsp(5,36) name = page type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_html_005frewrite_005f2.setPage("/paginas/comunes/jQuery/js/jquery.min.js");
      int _jspx_eval_html_005frewrite_005f2 = _jspx_th_html_005frewrite_005f2.doStartTag();
      if (_jspx_th_html_005frewrite_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fhtml_005frewrite_0026_005fpage_005fnobody.reuse(_jspx_th_html_005frewrite_005f2);
      _jspx_th_html_005frewrite_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_html_005frewrite_005f2, _jsp_getInstanceManager(), _jspx_th_html_005frewrite_005f2_reused);
    }
    return false;
  }
}
